### ISSUE TITLE
Update issues

### ISSUE THREAD

**Issue by dl5rcw** [tine20/tine20#7142] opened 2020-01-28 13:50 UTC
running update caused:

> /usr/share/tine20/Tasks/Setup/Update/Release11.php must not be used or autoloaded or required etc.

solution (quick fix)
`root@host:/usr/share/tine20# vim Tinebase/Setup/Update/Release11.php`

```
#echo __FILE__ . ' must not be used or autoloaded or required etc.' . PHP_EOL;
#exit(1);
```

Then I had:

> root@host:/usr/share/tine20# vim Tasks/Setup/Update/Release11.php

and just did the same for this 2nd file.

Any ideas? Using php7.3-fpm, debian buster, apache2 and tine20 installed from debian repository. Latest greatest of 2020-01-28.

> /usr/share/tine20/.user.ini looks like:
```
max_input_time=120
#include_path=.:/usr/share/tine20:/usr/share/tine20/library:/usr/share/tine20/vendor/zendframework/zendframework1/library:/etc/tine20
include_path=.:/usr/share/tine20:/usr/share/tine20/library:/etc/tine20:/usr/share/tine20/vendor/zendframework/zendframework1/library
open_basedir=/usr/share/tine20:/var/lib/tine20:/tmp:/usr/share/php:/etc/tine20:/var/log/tine20
session.gc_maxlifetime=86400
memory_limit=128M
upload_max_filesize=20M
post_max_size=20M

safe_mode=off
display_errors=off
log_errors=on
magic_quotes_gpc=off
magic_quotes_runtime=off
register_globals=off

max_execution_time=90
```

both logfiles of 
> /var/log/tine20/tine20.log
> /var/log/php7.3-fpm.log

give no information. The PHP building already fails early. Same for /var/log/apache2/error.log

**Comment by gerryfrancis** [comment] 2020-01-28 15:07
Duplicate of https://github.com/tine20/tine20/issues/7140 .

**Comment by dl5rcw** [comment] 2020-01-28 16:08
@gerryfrancis thanks! It takes two files to adjust, not just the one mentioned in #7140. The quick-fix here works on two productive servers.

**Comment by pschuele** [comment] 2020-01-29 07:32
thanks for reporting. we'll have a look - i think, those lines should be removed from the code.

**Closed** 2020-01-29 12:57 UTC
Labels: Bug, Duplicate, Update
