### ISSUE TITLE
0005186:
make attachments better visible / divide attachments better from the rest of the message pane

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2649] opened 2018-06-09 00:11 UTC
**Reported by kaystrobach on 7 Dec 2011 20:33**

**Version:** Maischa (2011-05-5)

Hi,

it would be nice, if attachments, would be better seperated from the message pane:

e.g. beside the message or like it&#039;s done in thunderbird ;

**Comment by pschuele** [comment] 2018-07-04 09:07
duplicate of #2605

**Closed by pschuele** 2018-07-04 09:07 UTC
Labels: Bug, Felamimail, Mantis
