### ISSUE TITLE
Read Status between Tine and email clients

### ISSUE THREAD

**Issue by My1** [tine20/tine20#7349] opened 2022-01-04 09:52 UTC
Version 2021.12.1
Apparently when you access the mails not only via Tine but also via for example an imap access to the same server the read status doesnt seem to be relayed to tine, are there any specific things I should look for in the logs?

one thing that I saw that looks important seems this bit:

```
e96afc - user - 2022-01-04T09:36:40+00:00 WARN (4): Felamimail_Backend_Imap::getSummary::482 Message data invalid: Array
(
    [MODSEQ] => Array
        (
            [0] => 223
        )

    [FLAGS] => Array
        (
            [0] => \Seen
        )

)
Array
(
    [1801] => Array
        (
            [MODSEQ] => Array
                (
                    [0] => 223
                )

            [FLAGS] => Array
                (
                    [0] => \Seen
                )

        )

)
```

**Comment by pschuele** [comment] 2022-06-21 15:57
hmm, yes that message looks suspicious. but we would need the full log (of an updateMessageCache request) to debug this further.
which mailserver are you running / trying to access?

**Comment by kiwimarc** [comment] 2023-05-02 07:20
Did there not come any update on this?

**Comment by pschuele** [comment] 2023-05-10 10:56
I think, that is a duplicate of #7458 ... closing this issue

**Closed by pschuele** 2023-05-10 10:56 UTC
Labels: Felamimail
