### ISSUE TITLE
0004002:
move button for adding/editing accounts to main menu of felamimail

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2072] opened 2018-06-08 21:26 UTC
**Reported by pschuele on 1 Mar 2011 13:36**

move button for adding/editing accounts to main menu of felamimail or to another reasonable place

**Comment by Gloirin** [comment] 2018-06-09 22:07
Related to #668

**Comment by pschuele** [comment] 2018-06-15 11:18
duplicate of #1646

**Closed by pschuele** 2018-06-15 11:18 UTC
Labels: Feature Request, Felamimail, Mantis
