### ISSUE TITLE
can't save username / password at login page

### ISSUE THREAD

**Issue by mmrohloff** [tine20/tine20#6941] opened 2018-10-18 08:35 UTC
In Firefox it is not possible to save the username and password at the login page. Works with any other website.

**Comment by koelschejung74** [comment] 2018-10-19 18:38
which Version of tine and firefox did you used? Can you see any logs? What did say the console from firefox?

**Comment by lab-at-nohl** [comment] 2018-10-20 22:56
I think this is intended behaviour. You can configure that the last username is preselected, although. 

In my view you are talking about the browser's password store. If you want this, you need to setup a normal HTML page including a login form.

**Comment by mmrohloff** [comment] 2018-10-22 08:47
I use the latest version of Firefox Version 62.0.3 (64-Bit) / Ubuntu 18.04. Tine 2.0 Version: Caroline
(2017.11.13). And yes I would like to use the internal password store of Firefox. I am not very familiar with web development so please tell me what console output you need and where to find it.

**Comment by lab-at-nohl** [comment] 2018-10-22 20:43
As I said, I am pretty sure internal password store cannot be used here (the form is rendered by javascript and not part of the HTML source). Try to set up a HTML file including the login-form.

**Comment by pschuele** [comment] 2018-10-26 10:32
this is working in Chrome (and derivatives). maybe Firefox is getting this feature at some point, too.

I don't think we can do something about it here (at least if we don't want to rewrite the login page). closing this.

**Closed by pschuele** 2018-10-26 10:32 UTC
