### ISSUE TITLE
Active Sync stops working. (Outlook 2016 & 2019)

### ISSUE THREAD

**Issue by anio89** [tine20/tine20#6968] opened 2018-11-30 13:30 UTC
Hello, 

since some days i got some problems with a new Sync of my Outlook 2019 and 2016. 

First the sync works very fine but then it stops. After this Outlook is saying, that the folder is up to date. But this is wrong, because many of my E-Mails are missing. 

In the webinterface the folders are really up to date. So it seems to me, that is something wrong with my devices. 

Someone got the same problem? 

Thanks a lot for helping me.

**Comment by pschuele** [comment] 2018-12-03 09:33
hi,

do you see any errors in the server logfiles?

**Comment by pschuele** [comment] 2018-12-05 08:47
looks like there is a permission problem: the webserver might not be able to read all files below /var/www/vhosts/example.de/tine.example.de/. could you please check that?

**Comment by krie9er** [comment] 2018-12-09 14:52
Hi I'm working on the Server together with @anio89.

I've checked the permissions and they are set to 0644 with the Right user and Group.

Curious is, that active sync works an Android and iOS devices. only MS-Outlook has a Problem.

Any other suggestions? Thanks a lot!

**Comment by pschuele** [comment] 2018-12-10 09:04
please have a second look into the logfiles. the excerpt above has nothing to do with the problematic ActiveSync request. maybe you should put the log in DEBUG (7) mode and have a look for outlook-ActiveSync requests.

**Comment by krie9er** [comment] 2018-12-10 10:04
> please have a second look into the logfiles. the excerpt above has nothing to do with the problematic ActiveSync request. maybe you should put the log in DEBUG (7) mode and have a look for outlook-ActiveSync requests.

Hey thanks for the reply!
After some interrogation we found, that the Problem is related to only some users. We need to check, if the problem is connected to some local-network-issues, or to the user inside tine2.0

**Comment by pschuele** [comment] 2018-12-11 07:30
ok, waiting for more feedback :)

**Comment by estradis** [comment] 2019-01-09 12:16
F'up, because we have the same problem, but different behavior.

In our testlab we upgraded tine to 2018.08.8. After that all clients are not longer able to use active sync properly. 

In the anonymized apache log file I can see, that every POST method will result 404 (not found), but the OPTIONS method works correct:
`
www.xxx.yyy.zzz - - [09/Jan/2019:12:59:20 +0100] "OPTIONS /Microsoft-Server-ActiveSync HTTP/1.1" 200 3915 "-" "Thunderbird ActiveSync Lightning/6.2.4"
www.xxx.yyy.zzz - - [09/Jan/2019:12:59:20 +0100] "POST /Microsoft-Server-ActiveSync?Cmd=Settings&User=testlab%5Cjdoe&DeviceType=TbSync&DeviceId=MZTB1a082255e20aa4a5b93959e95b2e HTTP/1.1" 404 584 "-" "Thunderbird ActiveSync Lightning/6.2.4"
www.xxx.yyy.zzz - - [09/Jan/2019:12:59:40 +0100] "POST /Microsoft-Server-ActiveSync?jREHBBCGvaScOuH3U0dTpSV7ifx5BAAAAAALV2luZG93c01haWw= HTTP/1.1" 404 4278 "-" "-"
www.xxx.yyy.zzz - - [09/Jan/2019:12:59:41 +0100] "OPTIONS /Microsoft-Server-ActiveSync?User=jdoe&DeviceId=86BDA49C3AE1F7534753A5257B89FC79&DeviceType=WindowsMail HTTP/1.1" 200 3915 "-" "MSFT-WIN-3/10.0.17134"
www.xxx.yyy.zzz - - [09/Jan/2019:12:59:41 +0100] "POST /Microsoft-Server-ActiveSync?jREHBBCGvaScOuH3U0dTpSV7ifx5BAAAAAALV2luZG93c01haWw= HTTP/1.1" 404 584 "-" "-"
www.xxx.yyy.zzz - - [09/Jan/2019:12:59:41 +0100] "POST /Microsoft-Server-ActiveSync?jQkHBBCGvaScOuH3U0dTpSV7ifx5BAAAAAALV2luZG93c01haWw= HTTP/1.1" 404 4278 "-" "-"
www.xxx.yyy.zzz - - [09/Jan/2019:12:59:42 +0100] "OPTIONS /Microsoft-Server-ActiveSync HTTP/1.1" 200 3915 "-" "MSFT-WIN-3/10.0.17134"
www.xxx.yyy.zzz - - [09/Jan/2019:12:59:45 +0100] "OPTIONS /Microsoft-Server-ActiveSync?User=jdoe&DeviceId=86BDA49C3AE1F7534753A5257B89FC79&DeviceType=WindowsMail HTTP/1.1" 200 221 "-" "MSFT-WIN-3/10.0.17134"
www.xxx.yyy.zzz - - [09/Jan/2019:12:59:45 +0100] "POST /Microsoft-Server-ActiveSync?jREHBBCGvaScOuH3U0dTpSV7ifx5BAAAAAALV2luZG93c01haWw= HTTP/1.1" 404 584 "-" "-"
www.xxx.yyy.zzz - - [09/Jan/2019:12:59:45 +0100] "POST /Microsoft-Server-ActiveSync?jQkHBBCGvaScOuH3U0dTpSV7ifx5BAAAAAALV2luZG93c01haWw= HTTP/1.1" 404 4278 "-" "-"
www.xxx.yyy.zzz - - [09/Jan/2019:12:59:46 +0100] "OPTIONS /Microsoft-Server-ActiveSync HTTP/1.1" 200 3915 "-" "MSFT-WIN-3/10.0.17134"
`

But despite to logger priority 9 (undocumented) set, the tine20.log shows ABSOLUTE NOTHING ABOUT ACTIVE SYNC!

We already checked our server config, ownerships and groups as well as all permissions, but all is set correct. We believe, that the error must be somewhere in the activesync app, especially in handling of POST methods.

Or have the rewrite rules been changed?

> Hey thanks for the reply!
> After some interrogation we found, that the Problem is related to only some users. We need to check, if the problem is connected to some local-network-issues, or to the user inside tine2.0

@krie9er:
Have you found any solution for your problem? If so, would you be so kind and post it here?

**Comment by pschuele** [comment] 2019-01-10 07:56
> Or have the rewrite rules been changed?

I don't think so. but the 404 seems to point in that direction. you might activate rewrite logging in the webserver to check if there are any problems with that.

what happens if you open the url /Microsoft-Server-ActiveSync in the browser? do you only have problems with Outlook or also with other clients?

**Comment by pschuele** [comment] 2019-01-14 08:20
@anio89 ok, looks like the basic ActiveSync setup is working. so in the next step, we need a DEBUG log of the outlook sync / getFolders request

@estradis you might use the deb package to have the current rewrite configuration. or have a look at: https://github.com/tine20/tine20/blob/master/tine20/docs/htaccess (apache config)

**Comment by estradis** [comment] 2019-01-16 09:46
Thank you for providing the link to the htaccess file. I compared yours with mine, but there are no significant differences between them. (I only have other memory settings.) I also swapped the configurations, but there weren't any changes to the results. Ist always "File does not exist: /var/www/tine20/Microsoft-Server-ActiveSync"

**Comment by pschuele** [comment] 2019-01-16 13:01
>  Is always "File does not exist: /var/www/tine20/Microsoft-Server-ActiveSync"

that means that the rewrite rules are not (correctly) applied :(

**Comment by pschuele** [comment] 2019-01-21 11:12
hi, i think you need this before the rewrite rules:

```
 RewriteBase /tine20
```

**Comment by estradis** [comment] 2019-01-24 18:20
Thank you for you hint, but it didn't change anything. So I decided to restore former versions of configurations files from our repository. ActiveSync is now working again.

To complete this issue, I will share these configuration files as well.

**/etc/apache2/sites-enabled/tine.example.com.conf:**

```
# ====================================================== #
# !!!       THIS FILE IS CONTROLLED BY PUPPET        !!! #
# ====================================================== #
#     ANY CHANGES ON PUPPET CONTROLLED FILES WILL BE     #
#      OVERWRITTEN PERIODICALLY AND WITHOUT WARNING      #
# ====================================================== #
# 
<IfModule mod_ssl.c>
	<VirtualHost _default_:443>
		ServerAdmin webmaster@example.com
		ServerName  tine.example.com
		DocumentRoot  /var/www/tine.example.com/
		LogLevel info ssl:warn
		ErrorLog ${APACHE_LOG_DIR}/error.log
		CustomLog ${APACHE_LOG_DIR}/access.log combined
		Include conf-available/example.com-ssl.conf
		# MSc: In the first step redirect document root to tine20 path
		RewriteEngine on
		RewriteRule   ^/$  /tine20/  [R]
		# MSc: Then implement tine20 rules
		Include conf-available/tine20.conf
	</VirtualHost>
</IfModule>
```

And **/etc/apache2/conf-available/tine20.conf:**

```
# ====================================================== #
# !!!       THIS FILE IS CONTROLLED BY PUPPET        !!! #
# ====================================================== #
#     ANY CHANGES ON PUPPET CONTROLLED FILES WILL BE     #
#      OVERWRITTEN PERIODICALLY AND WITHOUT WARNING      #
# ====================================================== #
# 

Alias /tine20                      /var/www/tine.example.com/tine20
Alias /Microsoft-Server-ActiveSync /var/www/tine.example.com/tine20/Microsoft-Server-ActiveSync

# MSc: Workaround to prevent missing hammer.js until this error is fixed
# (See details in https://forge.tine20.org/view.php?id=12998)
Alias /tinebase                    /var/www/tine.example.com/tine20/Tinebase
# End Workaround

<Directory /var/www/tine.example.com/tine20>
    Order Allow,Deny
    Allow from all
    DirectoryIndex index.php
    Options +ExecCGI

    <IfModule mod_php7.c>
        php_admin_value max_input_time          120
        php_admin_value include_path            .:/var/www/tine.example.com/tine20:/var/www/tine.example.com/tine20/library:/var/www/tine.example.com/tine20/vendor/zendframework/zendframework1/library:/etc/tine20
        php_admin_value open_basedir            /var/www/tine.example.com/tine20:/var/lib/tine20:/tmp:/usr/share/php:/etc/tine20:/var/log/tine20
        php_admin_value include_path            .:/var/www/tine.example.com/tine20:/var/www/tine.example.com/tine20/library:/var/www/tine.example.com/tine20/vendor/zendframework/zendframework1/library:/etc/tine20
        php_admin_value open_basedir            /var/www/tine.example.com/tine20:/var/lib/tine20:/tmp:/usr/share/php:/etc/tine20:/var/log/tine20
        php_admin_value open_basedir            /var/www/tine.example.com/tine20:/var/lib/tine20:/usr/share/php:/etc/tine20:/var/log/tine20:/var/www/tine.example.com/tine20:/var/lib/tine20:/usr/share/php:/tmp:		
        php_admin_value session.gc_maxlifetime  86400
        php_admin_value memory_limit            256M
        php_admin_value upload_max_filesize     20M
        php_admin_value post_max_size           20M
        php_admin_value safe_mode               off
        php_admin_flag  display_errors          off
        php_admin_flag  log_errors              on
        php_admin_flag  magic_quotes_gpc        off
        php_admin_flag  magic_quotes_runtime    off
        php_admin_flag  register_globals        off
        <IfModule mod_headers.c>
            php_admin_flag  zlib.output_compression on
            <FilesMatch "\.php$">
                Header unset Content-Length
            </FilesMatch>
        </IfModule>
        php_value       max_execution_time      90
    </IfModule>

    <IfModule mod_rewrite.c>
        RewriteEngine on
        RewriteBase /tine20
        RewriteRule ^Microsoft-Server-ActiveSync index.php?frontend=activesync         [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
        RewriteRule ^users/(.*)                  index.php?frontend=openid&username=$1 [L,QSA]
        RewriteCond %{REQUEST_METHOD} !^(GET|POST)$
        RewriteRule ^$                           index.php?frontend=webdav             [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
        RewriteRule ^addressbooks                index.php?frontend=webdav             [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
        RewriteRule ^calendars                   index.php?frontend=webdav             [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
        RewriteRule ^webdav                      index.php?frontend=webdav             [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
        RewriteRule ^principals                  index.php?frontend=webdav             [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
        RewriteRule ^remote.php                  index.php?frontend=webdav             [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
        RewriteRule ^download/get/(.*)           index.php?method=Download.downloadNode&path=$1 [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
        RewriteRule ^download/show/(.*)          index.php?method=Download.displayNode&path=$1  [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
    </IfModule>

    <IfModule mod_expires.c>
        ExpiresActive on
        ExpiresByType image/gif              "access plus 1 month"
        ExpiresByType image/jpeg             "access plus 1 month"
        ExpiresByType image/png              "access plus 1 month"
        ExpiresByType text/css               "access plus 1 month"
        ExpiresByType application/javascript "access plus 1 month"
    </IfModule>
    
    <IfModule mod_deflate.c>
        AddOutputFilterByType DEFLATE text/plain
        AddOutputFilterByType DEFLATE text/html
        AddOutputFilterByType DEFLATE text/css
        AddOutputFilterByType DEFLATE application/javascript
        AddOutputFilterByType DEFLATE application/json
        <IfModule mod_headers.c>
            Header append Vary User-Agent env=!dont-vary
        </IfModule>
    </IfModule>

</Directory>

<Location /tine20/Setup>
        Order Deny,Allow
        Deny from All
        Allow from 10.***.***.***/24
	Allow from fd**:****:****::/48
</Location>

<Location /tine20/setup.php>
        Order Deny,Allow
        Deny from All
        Allow from 10.***.***.***/24
	Allow from fd**:****:****::/48
</Location>
```

**Comment by pschuele** [comment] 2019-01-25 10:48
ok, thx @estradis .

@krie9er / @anio89 : do you already have more information regarding your problem?

**Comment by anio89** [comment] 2019-01-28 18:31
Hello, 
iam sorry for writing so late. But we are very busy at the Moment. 

The problem is not solved at the moment. We tried another pc with the newest Outlook Version and the Problem is still the same. 

@pschuele Can you tell what log file you need? Because i found no special Log files of Outlook. Is there a hidden option, where i can activate the loging of Outlook? 

Thanks a lot for helping.

**Comment by pschuele** [comment] 2019-01-29 09:12
> @pschuele Can you tell what log file you need? Because i found no special Log files of Outlook. Is there a hidden option, where i can activate the loging of Outlook?

we need the apache error.log and/or php-fpm-error.log and the tine20.log (with DEBUG level). you can send the by mail if you don't want to post them here.

**Comment by anio89** [comment] 2019-01-29 16:34
@pschuele 

You should recieved an e-mail.

**Comment by pschuele** [comment] 2019-01-30 08:49
yep, thx for that.

**Comment by anio89** [comment] 2019-06-02 20:33
Hi, 
sorry for writing so late. 

But i found a solution, how it is possible to recieve all new E-Mails. 

You only have to change the time of sync. 
=> So when you add your account to Outlook, you can choose how long it is synced. The normal option is "sync all time".  When you set it to "only" 1 Month - everything is working fine.

**Comment by pschuele** [comment] 2019-06-03 06:55
thanks for the update. maybe the memory limit on your webserver is not sufficient? you might try it by increasing it:

```
 php_admin_value memory_limit            512M

**Comment by anio89** [comment] 2019-06-03 13:08
@pschuele 

The Memorylimit is set to 512M. But this value is set via Plesk. 

We tried to increase this value up to 2GB - but it won't work.  Is it possible that the memory is also limit in a config file of tine ? 

Thansk for helping.

**Comment by pschuele** [comment] 2020-03-31 09:28
@anio89 nope, tine20 does not set the memory_limit in the php code. you might check the webserver or php-configs for "memory_limit". you can have a look at the current php-settings in the tine20 Admin area ("Server Information").

closing this issue - I lost track of the original problem. please open a new issue if the problem persists. thx!

**Closed by pschuele** 2020-03-31 09:28 UTC
Labels: ActiveSync, To be reproduced, Webserver
