### ISSUE TITLE
Creating new time-accout results in "Field 'contract' doesn't have a default value"

### ISSUE THREAD

**Issue by weberhofer** [tine20/tine20#6928] opened 2018-09-24 07:50 UTC
Trying to save a new time account results in an exception:
```
SQLSTATE[HY000]: General error: 1364 Field 'contract' doesn't have a default value, query was: INSERT INTO `tine20_timetracker_timeaccount` (`title`, `number`, `description`, `budget`, `budget_unit`, `price`, `price_unit`, `is_open`, `is_billable`, `billed_in`, `status`, `cleared_at`, `deadline`, `container_id`, `seq`, `is_deleted`, `created_by`, `creation_time`, `last_modified_by`, `last_modified_time`, `deleted_time`, `deleted_by`, `id`) VALUES (?, ?, ?, NULL, ?, NULL, ?, 1, 1, ?, ?, NULL, ?, ?, 1, 0, ?, ?, NULL, NULL, NULL, NULL, ?)
```
Allowing NULL in this row and setting the default value to NULL solves the problem.

**Comment by pschuele** [comment] 2018-09-24 08:31
hi,
which version are you using? there shouldn't be a row 'contract' in this table.

**Comment by weberhofer** [comment] 2018-09-24 09:57
It's version 2018.08.4; this is my personal instance which have been updates since years...

**Comment by pschuele** [comment] 2018-09-25 07:43
ok, as a hotfix, you can just drop the column "contract". I'll have a look at this.

**Comment by weberhofer** [comment] 2018-09-26 18:13
Thanks, I'll do that.

**Comment by mgeha** [comment] 2019-05-20 09:56
Hi there, having the some issue while trying to create a new time account. It's also an very old install which I update from time to time.

Tine Version 2019.02

`SQLSTATE[HY000]: General error: 1364 Field 'contract' doesn't have a default value, query was: INSERT INTO `tine20_timetracker_timeaccount` (`title`, `number`, `description`, `budget`, `budget_unit`, `price`, `price_unit`, `is_open`, `is_billable`, `billed_in`, `status`, `cleared_at`, `deadline`, `container_id`, `seq`, `is_deleted`, `created_by`, `creation_time`, `last_modified_by`, `last_modified_time`, `deleted_time`, `deleted_by`, `id`) VALUES (?, ?, ?, NULL, ?, NULL, ?, 1, 1, ?, ?, NULL, ?, ?, 1, 0, ?, ?, NULL, NULL, NULL, NULL, ?)`

Should I drop the column too or will I run into problems with Tine 2019.02?

**Comment by weberhofer** [comment] 2019-05-20 10:34
I have the same issue. I have allowed NULL to be set. I don't know if the column is still used, I think I have had dropped it some time ago but now it's in again.

**Comment by pschuele** [comment] 2020-03-31 09:23
this problem should be already fixed. please re-open the issue if not.

**Comment by hartundweich** [comment] 2020-07-03 11:11
Same here - using 2020.03.3. This installation is active since 10 years
Can I drop the column "contract"?

**Comment by weberhofer** [comment] 2020-07-03 12:32
I am sure, that I had dropped that column. But I had a look to my running version and: It has been re-created!

**Comment by pschuele** [comment] 2020-07-07 06:43
that is a strange one.

> Can I drop the column "contract"?

yep, just drop it.

> But I had a look to my running version and: It has been re-created!

are you sure? do you know when (in which version) this happened?

**Comment by weberhofer** [comment] 2020-07-07 08:18
Unfortunately I can't tell you; I could create new time-accounts on the beginning of June (using 2020.03.2), after Update to 2020.03.3 the column re-appeared; when I checked for this ticket, I recognized that the column has been back agein.

**Comment by pschuele** [comment] 2020-07-14 07:04
ok, this gets even stranger ... could you please have a look at Timetracker/Model/Timeaccount.php - is your local file identical to https://github.com/tine20/tine20/blob/main/tine20/Timetracker/Model/Timeaccount.php?

the table structure is generated by the doctrine schema tool. it uses the model fields and creates table columns for them (if they are not marked as "virtual" - as it is the case for "contract"):

```php
     'contract'       => array(
                'type'                  => 'virtual',
                'config'                => array(
                    'type'                  => 'relation',
                    'label'                 => 'Contract',    // _('Contract')
                    'config'                => array(
                        'appName'               => 'Sales',
                        'modelName'             => 'Contract',
                        'type'                  => 'TIME_ACCOUNT'
                    )
                )
            ),
```

so if your model is the same as the one in the repo, the schema tool might not work in your installation as it creates columns for virtual fields... can you tell us some more about your setup (php version, db)?

**Comment by hartundweich** [comment] 2020-07-14 07:23
Hello,

My Timeaccount.php is identical to this one you have posted.
Following setup: PHP 7.3.18
MySQL: 5.7.29

**Comment by weberhofer** [comment] 2020-07-14 08:22
I have the same section, too.
My environment has currently MariaDB 10.4.13 and PHP 7.4.6; I'm not sure if I had the same environment on updating Tine, as I did a distribution upgrade some weeks ago.

**Comment by pschuele** [comment] 2020-07-14 12:54
thanks for the info. I'll run a few tests and try to reproduce the problem.

**Comment by weberhofer** [comment] 2020-07-22 15:14
The update to 2020.0.4 did not re-create the column.

**Comment by pschuele** [comment] 2023-05-30 09:08
is this still a problem? if yes - please re-open

**Closed by pschuele** 2023-05-30 09:08 UTC
Labels: Timetracker, Update, To be reproduced
