### ISSUE TITLE
update on debian 2018.08.4-1.90 -> 2018.08.5-1.90: setup.php --update fails

### ISSUE THREAD

**Issue by tobser** [tine20/tine20#6958] opened 2018-11-06 20:21 UTC
since this update (from /var/log/apt/history.log):
```
Start-Date: 2018-10-30  02:26:17
Commandline: apt-get dist-upgrade
Upgrade: tine20-felamimail:amd64 (2018.08.4-1.90, 2018.08.5-1.90), tine20-tasks:amd64 (2018.08.4-1.90, 2018.08.5-1.90), tine20-activesync:amd64 (2018.08.4-1.90, 2018.08.5-1.90), tine20-mailfiler:amd64 (2018.08.4-1.90, 2018.08.5-1.90), tine20-humanresources:amd64 (2018.08.4-1.90, 2018.08.5-1.90), tine20-filemanager:amd64 (2018.08.4-1.90, 2018.08.5-1.90), tine20-sales:amd64 (2018.08.4-1.90, 2018.08.5-1.90), tine20-webstack:amd64 (2018.08.4-1.90, 2018.08.5-1.90), tine20-libraries:amd64 (2018.08.4-1.90, 2018.08.5-1.90), tine20-tinebase:amd64 (2018.08.4-1.90, 2018.08.5-1.90), tine20-inventory:amd64 (2018.08.4-1.90, 2018.08.5-1.90), tine20-crm:amd64 (2018.08.4-1.90, 2018.08.5-1.90), tine20-calendar:amd64 (2018.08.4-1.90, 2018.08.5-1.90), tine20:amd64 (2018.08.4-1.90, 2018.08.5-1.90), tine20-timetracker:amd64 (2018.08.4-1.90, 2018.08.5-1.90)
End-Date: 2018-10-30  02:26:26

```

the command 
`/usr/bin/php /usr/share/tine20/setup.php  --config /etc/tine20/config.inc.php  --update`

fails with the following exceptions
```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'tine20_humanresources_account' already exists in /usr/share/tine20/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104
Stack trace:
#0 /usr/share/tine20/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(104): PDO->query('CREATE TABLE `t...')
#1 /usr/share/tine20/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(852): Doctrine\DBAL\Driver\PDOConnection->query('CREATE TABLE `t...')
#2 /usr/share/tine20/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php(843): Doctrine\DBAL\Connection->executeQuery('CREATE TABLE `t...')
#3 /usr/share/tine20/Setup/SchemaTool.php(144): Doctrine\ORM\Tools\SchemaTool->updateSchema(Array, true)
#4 /usr/share/tine20/Setup/Update/Abstract.php(532): Setup_SchemaTool::updateSchema(Array)
#5 /usr/share/tine20/HumanResources/Setup/Update/Release12.php(15): Setup_Update_Abstract->updateSchema('HumanResources', Array)
#6 /usr/share/tine20/Setup/Controller.php(631): H in /usr/share/tine20/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 49

Fatal error: Uncaught PDOException: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'tine20_humanresources_account' already exists in /usr/share/tine20/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104
Stack trace:
#0 /usr/share/tine20/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(104): PDO->query('CREATE TABLE `t...')
#1 /usr/share/tine20/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(852): Doctrine\DBAL\Driver\PDOConnection->query('CREATE TABLE `t...')
#2 /usr/share/tine20/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php(843): Doctrine\DBAL\Connection->executeQuery('CREATE TABLE `t...')
#3 /usr/share/tine20/Setup/SchemaTool.php(144): Doctrine\ORM\Tools\SchemaTool->updateSchema(Array, true)
#4 /usr/share/tine20/Setup/Update/Abstract.php(532): Setup_SchemaTool::updateSchema(Array)
#5 /usr/share/tine20/HumanResources/Setup/Update/Release12.php(15): Setup_Update_Abstract->updateSchema('HumanResources', Array)
#6 /usr/share/tine20/Setup/Controller.php(631): H in /usr/share/tine20/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 49

```
and tine is stuck in maintenance mode.

packages are installed from 
`deb https://packages.tine20.org/debian stretch stable`

**Comment by pschuele** [comment] 2018-11-07 09:57
hi,

do you use the HumanResources module?
could you switch the tine20-logging to DEBUG and attach the logfile?

**Comment by pschuele** [comment] 2018-11-08 09:16
ok, somehow tine20 has the opinion that the HR module needs an update... when it tries to create the table(s), it crashes.

please try to uninstall the module (for example via CLI):

```
php setup.php --config=/path/to/config --uninstall HumanResources
```

and try again.

if that does not help, you might have to remove the tables (tine20_humanresources_*) manually.

**Comment by tobser** [comment] 2018-11-08 21:02
after uninstalling HumanResources I get a new error:
[tine20-update2.log](https://github.com/tine20/tine20/files/2563585/tine20-update2.log)

**Comment by pschuele** [comment] 2018-11-09 07:30
the new error is a duplicate of #6949 which is already fixed. closing this issue.

**Closed by pschuele** 2018-11-09 07:30 UTC
Labels: HumanResources, Update
