### ISSUE TITLE
"You need to run webpack-dev-server in dev mode! See https://wiki.tine20.org/Developers/Getting_Started/Working_with_GIT#Install_webpack" on setup.php after upgrade to 2019.12.2

### ISSUE THREAD

**Issue by cvantum** [tine20/tine20#7120] opened 2019-12-20 10:04 UTC
Hello,

we did an upgrade via repository on our server with Debian Stretch to 2019.12.2. Update working fine also second update-process with:

```
php /usr/share/tine20/setup.php --config /etc/tine20/config.inc.php --update
```

But now clients get displayed a white page when they enter the URLs. Also when i want to access **setup.php** via Browser i get this Message:

```
php /usr/share/tine20/setup.php --config /etc/tine20/config.inc.php --update
```

We have tine20 running on debug mode and cannot find any issues in `/var/log/tine20/tine20.log` also there are no php-errors in `/var/log/apache2/error.log`

If you need any further informations feel free to ask.

Thank you in advance,

Kind regards

**Comment by hartundweich** [comment] 2019-12-20 10:23
Same issue here - wanted to update from 2019.08.4 --> 2019.12.2
 
Placed new files for 2019.12.2 on server via FTP and when I run setup.php I only get:

`You need to run webpack-dev-server in dev mode! See https://wiki.tine20.org/Developers/Getting_Started/Working_with_GIT#Install_webpack`

Going back to 2019.08.4 until this is solved.

**Comment by cvantum** [comment] 2019-12-20 10:24
We found some informations in `/var/log/tine20/tine20.log`
```
3f139 - -- none -- - 2019-12-20T10:21:02+00:00 INFO (6): Tinebase_Core::setupLogger::838 Logger initialized.
3f139 - -- none -- - 2019-12-20T10:21:02+00:00 DEBUG (7): Tinebase_Session_Abstract::setSessionOptions::413 Session options: Array
(
    [name] => TINE20SETUPSESSID
    [cookie_httponly] => 1
    [hash_function] => 1
    [cookie_path] => /tine20
    [cookie_secure] => 1
)

3f139 - -- none -- - 2019-12-20T10:21:02+00:00 DEBUG (7): Tinebase_Core::setupCache::890 Cache logging disabled
3f139 - -- none -- - 2019-12-20T10:21:02+00:00 INFO (6): Tinebase_Core::setupCache::959 cache of backend type 'File' enabled
3f139 - -- none -- - 2019-12-20T10:21:02+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1080 Creating Pdo_Mysql DB adapter (db name: tine20)
3f139 - -- none -- - 2019-12-20T10:21:02+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1099 Using MySQL charset: utf8mb4
3f139 - -- none -- - 2019-12-20T10:21:02+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1118 Falling back to utf-8 charset
3f139 - -- none -- - 2019-12-20T10:21:02+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1132  connection id: 197
3f139 - -- none -- - 2019-12-20T10:21:02+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::685 Loading all configs for app Tinebase
3f139 - -- none -- - 2019-12-20T10:21:02+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::703 Found 16 configs.
3f139 - -- none -- - 2019-12-20T10:21:02+00:00 DEBUG (7): Tinebase_Session_Abstract::getSessionDir::198 Using session dir: /var/lib/tine20/sessions
3f139 - -- none -- - 2019-12-20T10:21:02+00:00 INFO (6): Tinebase_Session_Abstract::setSessionBackend::314 Session of backend type 'File' configured.
3f139 - -- none -- - 2019-12-20T10:21:02+00:00 DEBUG (7): Tinebase_Core::setExecutionLifeTime::1386 setting execution life time to: 0
3f139 - -- none -- - 2019-12-20T10:21:02+00:00 INFO (6): Tinebase_Core::setupCache::967 Cache disabled
3f139 - -- none -- - 2019-12-20T10:21:02+00:00 DEBUG (7): Tinebase_Translation::getLocale::199 given localeString 'en_US'
3f139 - -- none -- - 2019-12-20T10:21:03+00:00 DEBUG (7): Tinebase_Translation::getLocale::212 'en_US' is not supported, checking fallback
3f139 - -- none -- - 2019-12-20T10:21:03+00:00 DEBUG (7): Tinebase_Translation::getLocale::238 selected locale: 'en'
3f139 - -- none -- - 2019-12-20T10:21:03+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1253 given localeString 'auto'
3f139 - -- none -- - 2019-12-20T10:21:03+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1263 Got locale from session : de
3f139 - -- none -- - 2019-12-20T10:21:03+00:00 INFO (6): Tinebase_Core::setupUserLocale::1304 Setting user locale: de
3f139 - -- none -- - 2019-12-20T10:21:03+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1313 Setting CTYPE locale from "C" to "en_US.UTF8".
3f139 - -- none -- - 2019-12-20T10:21:03+00:00 DEBUG (7): Setup_Server_Http::handle::35 is http request. method: 
3f139 - -- none -- - 2019-12-20T10:21:03+00:00 DEBUG (7): Tinebase_Helper::getFileOrUriContents::435 Fetching content from http://localhost:10443/Tinebase/js/webpack-assets-FAT.json
3f139 - -- none -- - 2019-12-20T10:21:03+00:00 WARN (4): Tinebase_Core::errorHandler::701 stream_socket_client(): unable to connect to tcp://localhost:10443 (Connection refused) in /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Http/Client/Adapter/Socket.php::237 (2)
3f139 - -- none -- - 2019-12-20T10:21:03+00:00 WARN (4): Tinebase_Core::errorHandler::702 #0 [internal function]: Tinebase_Core::errorHandler(2, 'stream_socket_c...', '/usr/share/tine...', 237, Array)
#1 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Http/Client/Adapter/Socket.php(237): stream_socket_client('tcp://localhost...', 0, '', 10, 4, Resource id #118)
#2 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Http/Client.php(1073): Zend_Http_Client_Adapter_Socket->connect('tcp://localhost', '10443', false)
#3 /usr/share/tine20/Tinebase/Helper.php(438): Zend_Http_Client->request()
#4 /usr/share/tine20/Tinebase/Frontend/Http/SinglePageApplication.php(111): Tinebase_Helper::getFileOrUriContents('http://localhos...')
#5 /usr/share/tine20/Tinebase/Frontend/Http/SinglePageApplication.php(132): Tinebase_Frontend_Http_SinglePageApplication::getAssetsMap()
#6 /usr/share/tine20/Tinebase/Frontend/Http/SinglePageApplication.php(44): Tinebase_Frontend_Http_SinglePageApplication::getAssetHash()
#7 /usr/share/tine20/Setup/Frontend/Http.php(65): Tinebase_Frontend_Http_SinglePageApplication::getClientHTML(Array, 'Tinebase/views/...')
#8 [internal function]: Setup_Frontend_Http->mainScreen()
#9 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Server/Reflection/Function/Abstract.php(380): ReflectionMethod->invokeArgs(Object(Setup_Frontend_Http), Array)
#10 /usr/share/tine20/Tinebase/Http/Server.php(138): Zend_Server_Reflection_Function_Abstract->__call('invokeArgs', Array)
#11 /usr/share/tine20/Setup/Server/Http.php(46): Tinebase_Http_Server->handle(Array)
#12 /usr/share/tine20/Setup/Core.php(117): Setup_Server_Http->handle()
#13 /usr/share/tine20/setup.php(14): Setup_Core::dispatchRequest()
#14 {main}
3f139 - -- none -- - 2019-12-20T10:21:03+00:00 ERR (3): Tinebase_Exception::logExceptionToLogger::133 Zend_Http_Client_Adapter_Exception -> Unable to Connect to tcp://localhost:10443. Error #111: Connection refused options: Array
(
    [persistent] => 
    [ssltransport] => ssl
    [sslcert] => 
    [sslpassphrase] => 
    [sslusecontext] => 
    [verify_peer] => 
    [verify_peer_name] => 
    [maxredirects] => 5
    [strictredirects] => 
    [useragent] => Zend_Http_Client
    [timeout] => 10
    [httpversion] => 1.1
    [keepalive] => 
    [storeresponse] => 1
    [strict] => 1
    [output_stream] => 
    [encodecookies] => 1
    [rfc3986_strict] => 
)

3f139 - -- none -- - 2019-12-20T10:21:03+00:00 ERR (3): Tinebase_Exception::logExceptionToLogger::155 #0 .../vendor/zendframework/zendframework1/library/Zend/Http/Client.php(1073): Zend_Http_Client_Adapter_Socket->connect('tcp://localhost', '10443', false)
#1 .../Tinebase/Helper.php(438): Zend_Http_Client->request()
#2 .../Tinebase/Frontend/Http/SinglePageApplication.php(111): Tinebase_Helper::getFileOrUriContents('http://localhos...')
#3 .../Tinebase/Frontend/Http/SinglePageApplication.php(132): Tinebase_Frontend_Http_SinglePageApplication::getAssetsMap()
#4 .../Tinebase/Frontend/Http/SinglePageApplication.php(44): Tinebase_Frontend_Http_SinglePageApplication::getAssetHash()
#5 .../Setup/Frontend/Http.php(65): Tinebase_Frontend_Http_SinglePageApplication::getClientHTML(Array, 'Tinebase/views/...')
#6 [internal function]: Setup_Frontend_Http->mainScreen()
#7 .../vendor/zendframework/zendframework1/library/Zend/Server/Reflection/Function/Abstract.php(380): ReflectionMethod->invokeArgs(Object(Setup_Frontend_Http), Array)
#8 .../Tinebase/Http/Server.php(138): Zend_Server_Reflection_Function_Abstract->__call('invokeArgs', Array)
#9 .../Setup/Server/Http.php(46): Tinebase_Http_Server->handle(Array)
#10 .../Setup/Core.php(117): Setup_Server_Http->handle()
#11 .../setup.php(14): Setup_Core::dispatchRequest()
#12 {main}
3f139 - -- none -- - 2019-12-20T10:21:03+00:00 ERR (3): Tinebase_Frontend_Http_SinglePageApplication::Tinebase_Frontend_Http_SinglePageApplication::getAssetsMap (113) Could not get json file: Tinebase/js/webpack-assets-FAT.json
3f139 - -- none -- - 2019-12-20T10:21:03+00:00 ERR (3): Tinebase_Exception::logExceptionToLogger::133 Exception -> You need to run webpack-dev-server in dev mode! See https://wiki.tine20.org/Developers/Getting_Started/Working_with_GIT#Install_webpack
3f139 - -- none -- - 2019-12-20T10:21:03+00:00 ERR (3): Tinebase_Exception::logExceptionToLogger::155 #0 .../Tinebase/Frontend/Http/SinglePageApplication.php(132): Tinebase_Frontend_Http_SinglePageApplication::getAssetsMap()
#1 .../Tinebase/Frontend/Http/SinglePageApplication.php(44): Tinebase_Frontend_Http_SinglePageApplication::getAssetHash()
#2 .../Setup/Frontend/Http.php(65): Tinebase_Frontend_Http_SinglePageApplication::getClientHTML(Array, 'Tinebase/views/...')
#3 [internal function]: Setup_Frontend_Http->mainScreen()
#4 .../vendor/zendframework/zendframework1/library/Zend/Server/Reflection/Function/Abstract.php(380): ReflectionMethod->invokeArgs(Object(Setup_Frontend_Http), Array)
#5 .../Tinebase/Http/Server.php(138): Zend_Server_Reflection_Function_Abstract->__call('invokeArgs', Array)
#6 .../Setup/Server/Http.php(46): Tinebase_Http_Server->handle(Array)
#7 .../Setup/Core.php(117): Setup_Server_Http->handle()
#8 .../setup.php(14): Setup_Core::dispatchRequest()
#9 {main}
```

Looks like there should be a Websocket-Service which isn't runnning.

**Comment by hartundweich** [comment] 2019-12-20 10:36
> Looks like there should be a Websocket-Service which isn't runnning.

I think this socket should not be running - maybe there is a wrong check for a service that should not be running - I'm using tine for some years on my webspace provided by my DNS Provider - never had any troubles...

**Comment by j-a-n** [comment] 2019-12-20 11:17
Duplicate of #7118

**Comment by pschuele** [comment] 2019-12-20 11:26
we are currently building the new packages. sorry for the inconvenience!

**Closed by pschuele** 2019-12-20 11:26 UTC

**Comment by gongoscho** [comment] 2021-01-04 14:15
Thanks for the Information. I had the problem when i update from Version 2019.08.4 to 2019.12.1.

I skipped the Version 2019.12.1, and update from Version 2019.08.4 to Version 2019.12.5.

grEEtZ
