### ISSUE TITLE
0003988:
Feature request: provide a link for downloading all attachments at once

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2065] opened 2018-06-08 21:25 UTC
**Reported by kuyper on 24 Feb 2011 17:58**

If you get a mail with many attachments, clicking on each of them is rather nasty. Maybe there is a simple way of providing a link that downloads all of them. The software could trigger several downloads after each other? Maybe a zip file containing all attachments.

**Comment by pschuele** [comment] 2018-06-15 11:16
duplicate of #1217

**Closed by pschuele** 2018-06-15 11:16 UTC
Labels: Feature Request, Felamimail, Mantis, Usability
