### ISSUE TITLE
Update von 2018.08.04 auf 2018.08.05 geht schief - Uncaught Tinebase_Exception: waited for Action Queue

### ISSUE THREAD

**Issue by sit42** [tine20/tine20#6952] opened 2018-10-31 09:43 UTC
Nach dem Update der Ubuntu 18.04 Pakete von Tine und einem Neustart, wollten wir wie pblich noch per setup user im web frontend die Applikationen updaten.
Das waren
- Adressbook 12.2 -> 12.3
- Calendar 12.4-> 12.6
- HumanResources 12.0 -> 12.3
- Tinebase 12.5 -> 12.12

Egal ob ich nur tinebase oder eine andere Applikationen in der Web GUI updaten möchte, es kommt immer ein Fehler und ein Bericht wird gesendet.

Wenn ich es auf der Kommandozeile mache mit
sudo php -d "include_path=/etc/tine20" setup.php --update
dann bekommen wir

`PHP Fatal error:  Uncaught Tinebase_Exception: waited for Action Queue
to become empty for more than 300 sec in
/usr/share/tine20/Setup/Controller.php:752
Stack trace:
#0 /usr/share/tine20/Setup/Controller.php(614):
Setup_Controller->_prepareUpdate(Object(Tinebase_Model_FullUser))
#1 /usr/share/tine20/Setup/Controller.php(500):
Setup_Controller->updateApplication(Object(Tinebase_Model_Application),
'12')
#2 /usr/share/tine20/Setup/Frontend/Cli.php(546):
Setup_Controller->updateApplications(Object(Tinebase_Record_RecordSetFast))
#3 /usr/share/tine20/Setup/Frontend/Cli.php(502):
Setup_Frontend_Cli->_updateApplications()
#4 /usr/share/tine20/Setup/Frontend/Cli.php(73):
Setup_Frontend_Cli->_update(Object(Zend_Console_Getopt))
#5 /usr/share/tine20/Setup/Server/Cli.php(140):
Setup_Frontend_Cli->handle(Object(Zend_Console_Getopt))
#6 /usr/share/tine20/Setup/Core.php(115): Setup_Server_Cli->handle()
#7 /usr/share/tine20/setup.php(14): Setup_Core::dispatchRequest()
#8 {main}
  thrown in /usr/share/tine20/Setup/Controller.php on line 752
  
  Fatal error: Uncaught Tinebase_Exception: waited for Action Queue to
become empty for more than 300 sec in
/usr/share/tine20/Setup/Controller.php:752
Stack trace:
#0 /usr/share/tine20/Setup/Controller.php(614):
Setup_Controller->_prepareUpdate(Object(Tinebase_Model_FullUser))
#1 /usr/share/tine20/Setup/Controller.php(500):
Setup_Controller->updateApplication(Object(Tinebase_Model_Application),
'12')
#2 /usr/share/tine20/Setup/Frontend/Cli.php(546):
Setup_Controller->updateApplications(Object(Tinebase_Record_RecordSetFast))
#3 /usr/share/tine20/Setup/Frontend/Cli.php(502):
Setup_Frontend_Cli->_updateApplications()
#4 /usr/share/tine20/Setup/Frontend/Cli.php(73):
Setup_Frontend_Cli->_update(Object(Zend_Console_Getopt))
#5 /usr/share/tine20/Setup/Server/Cli.php(140):
Setup_Frontend_Cli->handle(Object(Zend_Console_Getopt))
#6 /usr/share/tine20/Setup/Core.php(115): Setup_Server_Cli->handle()
#7 /usr/share/tine20/setup.php(14): Setup_Core::dispatchRequest()
#8 {main}
  thrown in /usr/share/tine20/Setup/Controller.php on line 752`

Deshalb geht leider Tine aktuell nicht mehr.

Den Bugfix unter
"Applikationsupdate nach Upgrade auf Tine20 2018.08.5 geht schief" mit Nummer #6949
haben wir auch probiert. Aber das hat nichts gebracht.

Unser crontab als root sieht folgenermassen aus:
`### tine 2.0 cronjob - Neede to send invitation mails
*/5 * * * * php -d include_path=.:/usr/share/tine20:/usr/share/tine20/library:/etc/tine20 /usr/share/tine20/Calendar/Convert/Event/VCalendar/Tine.php --method Tinebase.triggerAsyncEvents >> /var/log/cron.log`

Bitte um Hilfe.
Wenn mehr Infos nötig sind, bitte Bescheid geben.

**Comment by topaDev** [comment] 2018-10-31 17:51
Steht doch eigentlich schon alles in den bereits vorhanden Threads - außer meiner Empfehlung, bei tine 2.0-Updates immer eine Woche zu warten...

**Comment by paulmhh** [comment] 2018-10-31 19:04
the ActionQueue is not AsyncEvents. I would assume you have configured a redis backend for the ActionQueue? Pls have a look at your configuration file. Maybe you want to remove that config and have your installation use the direct backend (default) instead of the redis backend?

If you want to continue to use the redis backend for the ActionQueue run
redis-cli flush-db
(on your own risk, you will loose *all* data in the redis, its supposed to be a cache, so that should be ok in theory)

**Comment by sit42** [comment] 2018-11-01 06:05
First of all: Thanks for the very fast answer/hints!!

Our config you can find attached as screenshot.
![grafik](https://user-images.githubusercontent.com/44637017/47835257-41507600-dda3-11e8-9c69-75accc2a4174.png)

1) "Waiting a week"
-> Yes usually we do this, but this time we have seen the new release and did not check the exact release date and installed .... Sorry.
PS: We are using Tine20 for years now and there is almost never a big problem updating to the newest version!! Big thanks for that!

And yes, probably we have to manually edit the mysql database of tine20. Which we usually are reluctant to do obviously...
We had changed the tine20/Calendar/Setup/Update/Release11.php script according to the other issue, but this probably gets not executed again? So the only way is manually editing the database?
Please advise.


2) "Redis"
Yes it looks like redis has been configured for the "Queue". This seems to be the default coming with the ubuntu packages. We have not changed this setting yet.
The config file for  the redis seems to be: (conf.d/worker.inc.php )
---

> <?php
> 
> /***** ACTION QUEUE *****/
> return array(
>     'actionqueue' =>
>         array(
>             'active' => true,
>             'backend' => 'Redis',
>             'host' => 'localhost',
>             'port' => 6379,
>             'queueName' => 'tine20worker'
>         ),
> );

---

**Comment by paulmhh** [comment] 2018-11-01 06:29
... the point is, if you dont run the Action Queue (../tine20/worker.php ... and as a demon...) it will never be actually executed. We'll discuss this and eventually fix it in the package.

in the meantime: as i said, either run redis-cli flush-db (for tine20 it is NOT a problem, if you dont have other applications on that redis it will be FINE) or just disable the Action Queue redis backend (what I would suggest, as you are not running the worker at all, all jobs pile up there without ever getting executed... not what you want!)

**Comment by sit42** [comment] 2018-11-01 12:45
Thanks for help.

I did a "redis-cli flushdb" and could now install tinebase and HumanResources" and a new package called courses.

BUT 
Adressbook 12.2 -> 12.3 and
Calendar 12.4-> 12.6
are still not working.

With running

I get an error like:
`php -d "include_path=/etc/tine20" setup.php --update
PHP Fatal error:  Uncaught Tinebase_Exception_NotFound: Tinebase_Model_Container record with id = 100 not found! in /usr/share/tine20/Tinebase/Backend/Sql/Abstract.php:282
Stack trace:
#0 /usr/share/tine20/Tinebase/Backend/Sql/Abstract.php(234): Tinebase_Backend_Sql_Abstract->getByProperty('100', 'id', false)
#1 /usr/share/tine20/Tinebase/Container.php(2043): Tinebase_Backend_Sql_Abstract->get('100', false)
#2 /usr/share/tine20/Calendar/Setup/Update/Release11.php(298): Tinebase_Container->update(Object(Tinebase_Model_Container))
#3 /usr/share/tine20/Calendar/Setup/Update/Release12.php(66): Calendar_Setup_Update_Release11->update_11()
#4 /usr/share/tine20/Setup/Controller.php(631): Calendar_Setup_Update_Release12->update_4()
#5 /usr/share/tine20/Setup/Controller.php(507): Setup_Controller->updateApplication(Object(Tinebase_Model_Application), '12')
#6 /usr/share/tine20/Setup/Frontend/Cli.php(546): Setup_Controller->updateApplications(Object(Tinebase_Record_RecordSetFast))
#7 /usr/share/tine20/Setup/Frontend/Cli.php(502): Setup_ in /usr/share/tine20/Tinebase/Backend/Sql/Abstract.php on line 282

Fatal error: Uncaught Tinebase_Exception_NotFound: Tinebase_Model_Container record with id = 100 not found! in /usr/share/tine20/Tinebase/Backend/Sql/Abstract.php:282
Stack trace:
#0 /usr/share/tine20/Tinebase/Backend/Sql/Abstract.php(234): Tinebase_Backend_Sql_Abstract->getByProperty('100', 'id', false)
#1 /usr/share/tine20/Tinebase/Container.php(2043): Tinebase_Backend_Sql_Abstract->get('100', false)
#2 /usr/share/tine20/Calendar/Setup/Update/Release11.php(298): Tinebase_Container->update(Object(Tinebase_Model_Container))
#3 /usr/share/tine20/Calendar/Setup/Update/Release12.php(66): Calendar_Setup_Update_Release11->update_11()
#4 /usr/share/tine20/Setup/Controller.php(631): Calendar_Setup_Update_Release12->update_4()
#5 /usr/share/tine20/Setup/Controller.php(507): Setup_Controller->updateApplication(Object(Tinebase_Model_Application), '12')
#6 /usr/share/tine20/Setup/Frontend/Cli.php(546): Setup_Controller->updateApplications(Object(Tinebase_Record_RecordSetFast))
#7 /usr/share/tine20/Setup/Frontend/Cli.php(502): Setup_ in /usr/share/tine20/Tinebase/Backend/Sql/Abstract.php on line 282
`
I did again redis-cli flushdb but it did not help.

Removing the "Redis" setting from the Queue settings did not work, because saving the configuration file from the Web GUI is not possible for some reason.

Sorry I am again lost here...

**Comment by paulmhh** [comment] 2018-11-01 14:19
this is a duplicate of #6949

**Closed by paulmhh** 2018-11-01 14:19 UTC
Labels: Update
