### ISSUE TITLE
Unable to change container permissions

### ISSUE THREAD

**Issue by ma-ef** [tine20/tine20#7254] opened 2021-01-01 19:38 UTC
When trying to edit the container permissions under Admin>Container>Edit Container there is no way to select users or groups. All existing users/groups are not found. Based on the debug log, it seems that something is wrong in the code:
**NOTICE (5): Tinebase_Core::errorHandler::746 Array and string offset access syntax with curly braces is deprecated in /var/www/effinger.org/htdocs/tine/vendor/zendframework/zendframework1/library/Zend/Json/Encoder.php::561 (8192)**

Full debug log:
63d3e4 d699e markus - 2021-01-01T16:20:20+00:00 INFO (6): Tinebase_Core::initFramework::467 initializing framework (PID: 505147)
63d3e4 d699e markus - 2021-01-01T16:20:20+00:00 DEBUG (7): Tinebase_Translation::getLocale::199 given localeString 'en_US'
63d3e4 d699e markus - 2021-01-01T16:20:20+00:00 DEBUG (7): Tinebase_Translation::getLocale::212 'en_US' is not supported, checking fallback
63d3e4 d699e markus - 2021-01-01T16:20:20+00:00 DEBUG (7): Tinebase_Translation::getLocale::238 selected locale: 'en'
63d3e4 d699e markus - 2021-01-01T16:20:20+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1295 given localeString 'auto'
63d3e4 d699e markus - 2021-01-01T16:20:20+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1305 Got locale from session : de
63d3e4 d699e markus - 2021-01-01T16:20:20+00:00 INFO (6): Tinebase_Core::setupUserLocale::1346 Setting user locale: de
63d3e4 d699e markus - 2021-01-01T16:20:20+00:00 DEBUG (7): Tinebase_Server_Json::_logRequests::226 is JSON request. rawdata: array (
  0 => 
  array (
    'jsonrpc' => '2.0',
    'method' => 'Addressbook.searchLists',
    'params' => 
    array (
      'filter' => 
      array (
        0 => 
        array (
          'field' => 'query',
          'operator' => 'contains',
          'value' => 'markus',
        ),
        1 => 
        array (
          'field' => 'type',
          'operator' => 'equals',
          'value' => 'group',
        ),
      ),
      'paging' => 
      array (
        'sort' => 'name',
        'dir' => 'ASC',
        'start' => 0,
        'limit' => 50,
      ),
    ),
    'id' => 3,
  ),
)
63d3e4 d699e markus - 2021-01-01T16:20:20+00:00 INFO (6): Tinebase_Server_Json::_handle::372 is JSON request. method: Addressbook.searchLists
63d3e4 d699e markus - 2021-01-01T16:20:20+00:00 DEBUG (7): Tinebase_User::setBackendType::322 Setting backend type to Ldap
63d3e4 d699e markus - 2021-01-01T16:20:20+00:00 DEBUG (7): Tinebase_Group::getInstance::83 groups backend: Ldap
63d3e4 d699e markus - 2021-01-01T16:20:20+00:00 DEBUG (7): Tinebase_Acl_Roles::getRoleMemberships::480 fetch role memberships from db
63d3e4 d699e markus - 2021-01-01T16:20:20+00:00 DEBUG (7): Tinebase_Acl_Roles::getApplications::180 fetch applications from db
63d3e4 d699e markus - 2021-01-01T16:20:20+00:00 DEBUG (7): Tinebase_Controller::userAccountChanged::931 check if userAccountChanged
63d3e4 d699e markus - 2021-01-01T16:20:20+00:00 DEBUG (7): Tinebase_Server_Json::_getServerClasses::500 fetching app json classes
63d3e4 d699e markus - 2021-01-01T16:20:20+00:00 NOTICE (5): Tinebase_Core::errorHandler::746 Array and string offset access syntax with curly braces is deprecated in /var/www/server/htdocs/tine/vendor/zendframework/zendframework1/library/Zend/Json/Encoder.php::561 (8192)
63d3e4 d699e markus - 2021-01-01T16:20:20+00:00 NOTICE (5): Tinebase_Core::errorHandler::747 #0 /var/www/server/htdocs/tine/vendor/composer/ClassLoader.php(444): Tinebase_Core::errorHandler()
#1 /var/www/server/htdocs/tine/vendor/composer/ClassLoader.php(444): include()
#2 /var/www/server/htdocs/tine/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#4 /var/www/server/htdocs/tine/Tinebase/Server/Json.php(313): spl_autoload_call()
#5 /var/www/server/htdocs/tine/Tinebase/Server/Json.php(391): Tinebase_Server_Json::_getServer()
#6 /var/www/server/htdocs/tine/Tinebase/Server/Json.php(167): Tinebase_Server_Json->_handle()
#7 /var/www/server/htdocs/tine/Tinebase/Core.php(267): Tinebase_Server_Json->handle()
#8 /var/www/server/htdocs/tine/index.php(24): Tinebase_Core::dispatchRequest()
#9 {main}
63d3e4 d699e markus - 2021-01-01T16:20:20+00:00 NOTICE (5): Tinebase_Core::errorHandler::746 Array and string offset access syntax with curly braces is deprecated in /var/www/server/htdocs/tine/vendor/zendframework/zendframework1/library/Zend/Json/Encoder.php::562 (8192)
63d3e4 d699e markus - 2021-01-01T16:20:20+00:00 NOTICE (5): Tinebase_Core::errorHandler::747 #0 /var/www/server/htdocs/tine/vendor/composer/ClassLoader.php(444): Tinebase_Core::errorHandler()
#1 /var/www/server/htdocs/tine/vendor/composer/ClassLoader.php(444): include()
#2 /var/www/server/htdocs/tine/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#4 /var/www/server/htdocs/tine/Tinebase/Server/Json.php(313): spl_autoload_call()
#5 /var/www/server/htdocs/tine/Tinebase/Server/Json.php(391): Tinebase_Server_Json::_getServer()
#6 /var/www/server/htdocs/tine/Tinebase/Server/Json.php(167): Tinebase_Server_Json->_handle()
#7 /var/www/server/htdocs/tine/Tinebase/Core.php(267): Tinebase_Server_Json->handle()
#8 /var/www/server/htdocs/tine/index.php(24): Tinebase_Core::dispatchRequest()
#9 {main}
63d3e4 d699e markus - 2021-01-01T16:20:20+00:00 NOTICE (5): Tinebase_Core::errorHandler::746 Array and string offset access syntax with curly braces is deprecated in /var/www/server/htdocs/tine/vendor/zendframework/zendframework1/library/Zend/Json/Encoder.php::563 (8192)
63d3e4 d699e markus - 2021-01-01T16:20:20+00:00 NOTICE (5): Tinebase_Core::errorHandler::747 #0 /var/www/server/htdocs/tine/vendor/composer/ClassLoader.php(444): Tinebase_Core::errorHandler()
#1 /var/www/server/htdocs/tine/vendor/composer/ClassLoader.php(444): include()
#2 /var/www/server/htdocs/tine/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#4 /var/www/server/htdocs/tine/Tinebase/Server/Json.php(313): spl_autoload_call()
#5 /var/www/server/htdocs/tine/Tinebase/Server/Json.php(391): Tinebase_Server_Json::_getServer()
#6 /var/www/server/htdocs/tine/Tinebase/Server/Json.php(167): Tinebase_Server_Json->_handle()
#7 /var/www/server/htdocs/tine/Tinebase/Core.php(267): Tinebase_Server_Json->handle()
#8 /var/www/server/htdocs/tine/index.php(24): Tinebase_Core::dispatchRequest()
#9 {main}
63d3e4 d699e markus - 2021-01-01T16:20:20+00:00 NOTICE (5): Tinebase_Core::errorHandler::746 Array and string offset access syntax with curly braces is deprecated in /var/www/server/htdocs/tine/vendor/zendframework/zendframework1/library/Zend/Json/Encoder.php::568 (8192)
63d3e4 d699e markus - 2021-01-01T16:20:20+00:00 NOTICE (5): Tinebase_Core::errorHandler::747 #0 /var/www/server/htdocs/tine/vendor/composer/ClassLoader.php(444): Tinebase_Core::errorHandler()
#1 /var/www/server/htdocs/tine/vendor/composer/ClassLoader.php(444): include()
#2 /var/www/server/htdocs/tine/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#4 /var/www/server/htdocs/tine/Tinebase/Server/Json.php(313): spl_autoload_call()
#5 /var/www/server/htdocs/tine/Tinebase/Server/Json.php(391): Tinebase_Server_Json::_getServer()
#6 /var/www/server/htdocs/tine/Tinebase/Server/Json.php(167): Tinebase_Server_Json->_handle()
#7 /var/www/server/htdocs/tine/Tinebase/Core.php(267): Tinebase_Server_Json->handle()
#8 /var/www/server/htdocs/tine/index.php(24): Tinebase_Core::dispatchRequest()
#9 {main}
63d3e4 d699e markus - 2021-01-01T16:20:20+00:00 NOTICE (5): Tinebase_Core::errorHandler::746 Array and string offset access syntax with curly braces is deprecated in /var/www/server/htdocs/tine/vendor/zendframework/zendframework1/library/Zend/Json/Encoder.php::569 (8192)
63d3e4 d699e markus - 2021-01-01T16:20:20+00:00 NOTICE (5): Tinebase_Core::errorHandler::747 #0 /var/www/server/htdocs/tine/vendor/composer/ClassLoader.php(444): Tinebase_Core::errorHandler()
#1 /var/www/server/htdocs/tine/vendor/composer/ClassLoader.php(444): include()
#2 /var/www/server/htdocs/tine/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#4 /var/www/server/htdocs/tine/Tinebase/Server/Json.php(313): spl_autoload_call()
#5 /var/www/server/htdocs/tine/Tinebase/Server/Json.php(391): Tinebase_Server_Json::_getServer()
#6 /var/www/server/htdocs/tine/Tinebase/Server/Json.php(167): Tinebase_Server_Json->_handle()
#7 /var/www/server/htdocs/tine/Tinebase/Core.php(267): Tinebase_Server_Json->handle()
#8 /var/www/server/htdocs/tine/index.php(24): Tinebase_Core::dispatchRequest()
#9 {main}
63d3e4 d699e markus - 2021-01-01T16:20:20+00:00 NOTICE (5): Tinebase_Core::errorHandler::746 Array and string offset access syntax with curly braces is deprecated in /var/www/server/htdocs/tine/vendor/zendframework/zendframework1/library/Zend/Json/Encoder.php::570 (8192)
63d3e4 d699e markus - 2021-01-01T16:20:20+00:00 NOTICE (5): Tinebase_Core::errorHandler::747 #0 /var/www/server/htdocs/tine/vendor/composer/ClassLoader.php(444): Tinebase_Core::errorHandler()
#1 /var/www/server/htdocs/tine/vendor/composer/ClassLoader.php(444): include()
#2 /var/www/server/htdocs/tine/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#4 /var/www/server/htdocs/tine/Tinebase/Server/Json.php(313): spl_autoload_call()
#5 /var/www/server/htdocs/tine/Tinebase/Server/Json.php(391): Tinebase_Server_Json::_getServer()
#6 /var/www/server/htdocs/tine/Tinebase/Server/Json.php(167): Tinebase_Server_Json->_handle()
#7 /var/www/server/htdocs/tine/Tinebase/Core.php(267): Tinebase_Server_Json->handle()
#8 /var/www/server/htdocs/tine/index.php(24): Tinebase_Core::dispatchRequest()
#9 {main}
63d3e4 d699e markus - 2021-01-01T16:20:20+00:00 NOTICE (5): Tinebase_Core::errorHandler::746 Array and string offset access syntax with curly braces is deprecated in /var/www/server/htdocs/tine/vendor/zendframework/zendframework1/library/Zend/Json/Encoder.php::571 (8192)
63d3e4 d699e markus - 2021-01-01T16:20:20+00:00 NOTICE (5): Tinebase_Core::errorHandler::747 #0 /var/www/server/htdocs/tine/vendor/composer/ClassLoader.php(444): Tinebase_Core::errorHandler()
#1 /var/www/server/htdocs/tine/vendor/composer/ClassLoader.php(444): include()
#2 /var/www/server/htdocs/tine/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#4 /var/www/server/htdocs/tine/Tinebase/Server/Json.php(313): spl_autoload_call()
#5 /var/www/server/htdocs/tine/Tinebase/Server/Json.php(391): Tinebase_Server_Json::_getServer()
#6 /var/www/server/htdocs/tine/Tinebase/Server/Json.php(167): Tinebase_Server_Json->_handle()
#7 /var/www/server/htdocs/tine/Tinebase/Core.php(267): Tinebase_Server_Json->handle()
#8 /var/www/server/htdocs/tine/index.php(24): Tinebase_Core::dispatchRequest()
#9 {main}
63d3e4 d699e markus - 2021-01-01T16:20:20+00:00 DEBUG (7): Tinebase_Server_Json::_getServer::316 Get server from cache
63d3e4 d699e markus - 2021-01-01T16:20:20+00:00 DEBUG (7): Tinebase_Server_Json::_handle::394 handle request ...
63d3e4 d699e markus - 2021-01-01T16:20:20+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::688 Loading all configs for app Addressbook
63d3e4 d699e markus - 2021-01-01T16:20:20+00:00 DEBUG (7): Tinebase_Config_Abstract::_getAppDefaultsConfigFileData::607 Looking for defaults config.inc.php at /var/www/server/htdocs/tine/Addressbook/config.inc.php
63d3e4 d699e markus - 2021-01-01T16:20:20+00:00 DEBUG (7): Tinebase_Config_Abstract::featureEnabled::993 Features config of app Addressbook: Array
(
    [featureContactEventList] => 1
    [featureListView] => 1
    [featureIndustry] => 1
    [featureMailinglist] => 
    [featureShortName] => 
    [featureResources] => 1
    [featureStructurePanel] => 1
)

63d3e4 d699e markus - 2021-01-01T16:20:20+00:00 DEBUG (7): Tinebase_Config_Abstract::featureEnabled::993 Features config of app Tinebase: Array
(
    [featureShowAdvancedSearch] => 1
    [featureShowAccountEmail] => 1
    [featureRememberPopupSize] => 1
    [featureCreatePreviews] => 
    [featureFullTextIndex] => 1
    [featureSearchPath] => 1
    [autodiscover] => 1
    [autodiscoverMailConfig] => 1
)

63d3e4 d699e markus - 2021-01-01T16:20:20+00:00 DEBUG (7): Tinebase_Core::setupUserTimezone::1410 User timezone: Europe/Berlin
63d3e4 d699e markus - 2021-01-01T16:20:20+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::checkFilterACL::2390 Force a standard containerFilter (specialNode = all) as ACL filter.
63d3e4 d699e markus - 2021-01-01T16:20:20+00:00 DEBUG (7): Tinebase_Container::getContainerByACL::468 app: Addressbook / account: markus / grant:readGrant/adminGrant
63d3e4 d699e markus - 2021-01-01T16:20:20+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::search::303 Got 0 search results of Addressbook_Model_List
63d3e4 d699e markus - 2021-01-01T16:20:20+00:00 INFO (6): Tinebase_Log::logUsageAndMethod::298 {"file":"index.php","method":"Tinebase_Server_Json::Addressbook.searchLists","time":"163ms","memory":" Memory usage: 2 MB","cache":" Real patch cache size: 301149","pid":505147}
2

**Comment by lab-at-nohl** [comment] 2021-01-03 19:23
To your NOTICE I find several issues over the net related to `PHP 7.4`. Also, see `zendframework/zendframework1/library/Zend/Json/Encoder.php` lines 560 ff. Here you find those brackets mentioned in the NOTICE. You could change them manually to `[]` but this would be reverted during the next update...

Within my test setting I can add containers like e.g. shared Adressbook / Lists. However, I use `PHP 7.3.24`. Can you try `PHP 7.2` or `PHP 7.3`? This might be **not the root cause** because it is NOTICE -- not **ERR**. If it is definitely related to `PHP 7.4`, @tine20 have to deal with it...

**Comment by pschuele** [comment] 2021-01-05 16:25
that problem should be already fixed in current versions (2020.08+). please update your tine20 server.

**Comment by ma-ef** [comment] 2021-01-06 09:03
Thanks for looking into this. Just to clarify: I am already running the latest version of tine - version: 2020.08 (2020.08.7) and the issue has occurred with this version. 

Running an LTS version of Ubuntu (Ubuntu 20.04.1 LTS) that uses PHP 7.4 I would expect that this PHP version is supported..

**Comment by pschuele** [comment] 2021-01-12 07:50
> Thanks for looking into this. Just to clarify: I am already running the latest version of tine - version: 2020.08 (2020.08.7) and the issue has occurred with this version.

ah, I see. sorry for that, you are right: https://github.com/tine20/zendframework1/blob/master/library/Zend/Json/Encoder.php still has the deprecated syntax. we'll fix that.

**Comment by pschuele** [comment] 2021-01-12 10:11
-> https://github.com/tine20/zendframework1/pull/18

**Closed** 2021-01-13 07:57 UTC
Labels: Bug, Tinebase, Update
