### ISSUE TITLE
0009662:
user instant messaging

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#4847] opened 2018-06-09 10:07 UTC
**Reported by khalili on 10 Feb 2014 15:58**

**Version:** Collin (2013.10.4)

it would be very useful if users can send msg ( chat IM ) together .
for example sales persons can IM to each other . 

**Additional information:** using PHPOpenChat engine would make this easier

**Comment by pschuele** [comment] 2018-07-19 15:55
duplicate of #4323

**Closed by pschuele** 2018-07-19 15:55 UTC
Labels: Feature Request, Mantis
