### ISSUE TITLE
0005870:
Chat System

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2990] opened 2018-06-09 01:43 UTC
**Reported by kjmiami23 on 25 Feb 2012 09:09**

**Version:** Milan (2012-03) Beta 5

It would be good to have a closer communication and instant with clients and staff by having a chat system which is similar to egroupware and found egroupware is very fast aswell. This would be a good idea to implement into tine.

**Comment by pschuele** [comment] 2018-07-19 12:20
duplicate of #4323

**Closed** 2018-07-19 12:21 UTC
Labels: Duplicate, Feature Request, Mantis
