### ISSUE TITLE
Unable to install tine 2019.12.2

### ISSUE THREAD

**Issue by jameswill** [tine20/tine20#7121] opened 2019-12-20 11:13 UTC
Hi,

I was trying to install tine 209.12.2 on my server with PHP 7.0, Mysql 5.7 but unable to do so.

I have successfully completed installation through "php setup.php --config /{PATH}/tine2019122/config.inc.php --install However when I visit "http://{host}/{path}/tine2019122/setup.php" it throws following error.

You need to run webpack-dev-server in dev mode! See https://wiki.tine20.org/Developers/Getting_Started/Working_with_GIT#Install_webpack 

Can anyone help me out ? what is causing this issue ?

**Comment by pschuele** [comment] 2019-12-20 11:27
duplicate of #7118

**Closed by pschuele** 2019-12-20 11:27 UTC
