### ISSUE TITLE
0007074:
Feature Request: Admin ability to deactivate personal task lists

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3584] opened 2018-06-09 04:31 UTC
**Reported by mathijsen on 7 Sep 2012 14:49**

Would be fine if the admin would be able to deactivate personal tasks lists for users.

**Comment by Gloirin** [comment] 2018-06-09 23:53
Related to #3583

**Comment by pschuele** [comment] 2018-09-20 12:48
duplicate of #3581

**Closed by pschuele** 2018-09-20 12:48 UTC
Labels: Feature Request, Mantis, Tasks
