### ISSUE TITLE
0004646:
Add option: selected email is not automatically marked as read

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2382] opened 2018-06-08 22:53 UTC
**Reported by BoehserWolf on 26 Jul 2011 08:14**

**Version:** Maischa (2011-05-1)

When selecting an email the email is automatically marked as read. There should be an option to allow to enable/disable this behavior.
So the new option should allow the user to read an email by selecting the subject. Only when the user right-clicks and chooses &quot;mark as read&quot; or when the user opens an email by double-clicking, it will be marked as read.

**Additional information:** Tested with version 2011.05.1-2 from the debian stable repository.

**Comment by Gloirin** [comment] 2018-06-10 11:10
**Comment posted by mkl on 22 Dec 2013 20:28**

I agree with BoehserWolf, that&#039;s a really annoying bug.
Mails getting marked as read when the focus is on its list entry, even when the preview window is closed.

**Comment by Gloirin** [comment] 2018-06-10 11:11
**Comment posted by pschuele on 23 Dec 2013 09:05**

@Heiko: what do you think about this? maybe the &quot;marking as read&quot;-behavior should be improved before adding an option as proposed?

**Comment by Gloirin** [comment] 2018-06-10 11:11
**Comment posted by htietze on 27 Dec 2013 10:31**

As mkl says any item must not change its state on simple hovering. But I cannot confirm this behavior, at least with the demo (2013.10.2pl23).

Nevertheless I think its a good idea to have an option how emails are marked as read. Sometimes user might want to &#039;browse&#039; through the list of new emails and keep it marked as unread for later inspection. But when I know from the header that it is spam (or a bunch of reply to a mailing list I read somewhere else) I delete it rather fast and don&#039;t want to have it marked as unread in trash.

The usual answer to the reported issue is to not change the flag until a certain, user-defined time is passed (as shown in the scribble). Hopefully, this solves BoehserWolf&#039;s problem. And I agree to mark the mail as read when it is opened explicitly by double click regardless from the setting.

**Comment by Gloirin** [comment] 2018-06-10 11:11
**Comment posted by pschuele on 27 Dec 2013 13:38**

ok, thanks for you thoughts, they sound reasonable.

**Comment by pschuele** [comment] 2018-06-21 14:44
duplicate of #1771

**Closed by pschuele** 2018-06-21 14:44 UTC
Labels: Feature Request, Felamimail, Mantis
