### ISSUE TITLE
0005516:
Implement ActiveSync Autodiscover

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2813] opened 2018-06-09 00:41 UTC
**Reported by lab-at-nohl on 2 Feb 2012 21:11**

Summary explains it all...

http://www.tine20.org/forum/viewtopic.php?f=12&amp;t=10398
http://mein-edv-blog.de/?p=172
http://technet.microsoft.com/en-us/library/bb124251.aspx
http://msdn.microsoft.com/en-us/library/exchange/hh352638%28v=exchg.140%29.aspx

**Comment by Gloirin** [comment] 2018-06-10 13:12
**Comment posted by robi on 25 Jun 2013 15:50**

What rewrite rule needs to be added to apache config to make autodiscover service work?

I tried this, but it doesn&#039;t work:
RewriteRule /autodiscover/autodiscover.xml /var/www/tine/index.php

http://www.tine20.org/forum/viewtopic.php?f=8&amp;t=14638

**Comment by Gloirin** [comment] 2018-06-10 13:12
**Comment posted by lab-at-nohl on 26 Dec 2015 16:09**

Not all major clients handle Autodiscover as they are expected. Andorid/GMail 5.1.1 does it very wrong. 

There&#039;re two ways to get Autodiscover data, first try http(s) requests and if no informations is provided clients ought to try DNS entries. Expected is this order (for example user@domain.tld): 

1. Get &quot;domain&quot;-Info from Windows-Domain and ask there: https://windomain/Autodiscover/Autodiscover.xml (obviously doesn&#039;t work outside like in the internet). 

2. Use &quot;domain&quot; part from email and ask https://autodiscover.domain/Autodiscover/Autodiscover.xml (this is what iPhones try first). 

3. Like above but aks at https://domain/Autodiscover/Autodiscover.xml (circumstances are unclear; fallback for iPhones) 

4. Without credentials and without SSL aks at http://domain/Autodiscover/Autodiscover.xml and expect a 302-Redirect to an https-Autodiscovery, probably expects a special redirect-xml-response. 

5. Ask SRV-entry in DNS (Android doesn&#039;t at all). 

Clients are expected to send/receive xml. 

This is what Android 5.1.1 does: 

- Get MX-entry from DNS (for user@domain.tld -&gt; MX mail.mxexchange.tld) and aks at https://mxexchange.tld/Autodiscover/Autodiscover.xml (i.e. ask at top-level-domain). 

- The request is NOT sending proper xml, it is empty and uses method GET instead of POST (totally off-spec). 

- if proper xml is returned (examples you can google), Android only uses Host information (where to find /Microsoft-Server-ActiveSync). None the less better than nothing. 

I would push this topic to get an implementation in ActiveSync! Thanks, Johannes

**Comment by corneliusweiss** [comment] 2018-10-29 14:44
current iOS 12 queries for Autodiscover.json (at least with valid srv record)
https://www.msxfaq.de/exchange/autodiscover/autodiscover_v2.htm

**Comment by corneliusweiss** [comment] 2018-10-29 15:30
can't get it to work. 

`95.91.28.10 - - [29/Oct/2018:15:48:18 +0100] "GET /autodiscover/autodiscover.json?Email=nelius%40mydomain.de&Protocol=ActiveSync&RedirectCount=1 HTTP/1.1" 200 104 "-" "Apple-iPhone9C3/1602.506800009"
95.91.228.100 - - [29/Oct/2018:15:48:19 +0100] "GET /Microsoft-Server-ActiveSync HTTP/1.1" 401 5 "-" "Einstellungen/1.0 CFNetwork/975.0.3 Darwin/18.2.0"
95.91.228.100 - - [29/Oct/2018:15:48:19 +0100] "GET /Microsoft-Server-ActiveSync HTTP/1.1" 401 5 "-" "Einstellungen/1.0 CFNetwork/975.0.3 Darwin/18.2.0"`

**Comment by gongoscho** [comment] 2018-10-30 19:29
Hi,

i use this autodiscover. I think this is the best 🥇 
https://gist.github.com/rmpel/04a91680b87e358789ec

Work with HTTP & DNS requests

grEEtZ

**Comment by corneliusweiss** [comment] 2018-11-02 12:13
is it working with iOS 12 for you?

**Comment by gongoscho** [comment] 2018-11-03 07:07
I dont have iOS. I tested with android-, windows phone-, blackberry-, j2me - phones and outlook 2013 and outlook 2016

**Comment by corneliusweiss** [comment] 2018-11-07 21:40
can you send me a test account via pm?

**Comment by pschuele** [comment] 2019-01-09 08:45
tesla42 (from the matrix chat):

> Ich habe schließlich autodiscover ActiveSync hinbekommen:

https://github.com/TheTesla/ansible-tine/blob/master/roles/mailserver/templates/var/www/autodiscover/autodiscover/autodiscover.php
https://github.com/TheTesla/ansible-tine/blob/master/roles/mailserver/templates/etc/apache2/sites-available/autodiscover.conf
https://github.com/TheTesla/ansible-tine/blob/master/roles/mailserver/tasks/autodiscover.yml

**Comment by corneliusweiss** [comment] 2019-02-25 15:17
FYI: we implemented auto discovery nativ in our latest release. the extra vhost/project should not be necessary any longer

**Comment by lab-at-nohl** [comment] 2019-02-26 10:41
Wonderful. Could you add Rewrite rules to docs/htaccess? I guess all domains need to have subdomain autodiscover.domain.tld and refer autodicover/autodiscover.xml to index.php?

**Comment by corneliusweiss** [comment] 2019-02-26 17:15
no additional rewrites should be necessary as we have a catchall in the latest releases.

the autodiscover.xxx domain seems not to be necessary as well. clients  ask maildomain/auto... first and only autodiscover... if they don't get an answer there

**Comment by pschuele** [comment] 2019-03-07 08:02
closing this - implementation should be finished.

**Closed by pschuele** 2019-03-07 08:02 UTC
Labels: ActiveSync, Feature Request, Info in Forum, Mantis

**Comment by gongoscho** [comment] 2021-01-04 19:03
Hi there,

today I updated from v2019 to v2020.08.4 and AutoDiscover is now implemented, but I can't get it to work.

I copied the .htaccess from “tine20 / doc /”, but unfortunately it doesn't work. Tested with: https://testconnectivity.microsoft.com/tests/Eas/input

If I specify in the .htaccess:
RewriteRule ^ Autodiscover / Autodiscover.xml autodiscover.php

AutoDiscover works on (the script from the issue link).

Can somebody help me?

grEEtZ,
gongoscho

**Comment by lab-at-nohl** [comment] 2021-01-04 20:10
Are you aware that you are commenting inside a closed issue? 

I just tested your Microsoft-Tool, it worked very well with my installation (although secondary domains need a working redirect to main domain autodiscover). Please note that you have to enter the username as following `primarydomain\username`. 

I am pretty sure you have to include something like: https://github.com/tine20/tine20/blob/a3bca618442017b5af4bb84d8f3541161a43b3da/tine20/docs/htaccess#L49-L56
This looks like a default routing to me. Because Autodiscover expects a file `autodiscover/autodiscover.xml`.

**Comment by gongoscho** [comment] 2021-01-04 20:41
Yeah, sorry for that. When i search for a solution i found this old issue.

I have exactly this in my .htaccess but without `<Location /> <Location />` because i have my tine 2.0 on a webspace from german hoster: all-inkl.com and with the location-tag it is not working.

The only difference is, i have my tine in an subfolder:
```
# Routing 
RewriteCond %{REQUEST_FILENAME} -s [OR] 
RewriteCond %{REQUEST_FILENAME} -l [OR] 
RewriteCond %{REQUEST_FILENAME} -d 
RewriteRule ^.*$ - [NC,L] 
RewriteRule ^.*$ /folder/tine/index.php?doRouting=1 [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
```

The error:

> The Microsoft Connectivity Analyzer is attempting to retrieve an XML Autodiscover response from URL https://domain.tld.:443/Autodiscover/Autodiscover.xml for user xyz.The Microsoft Connectivity Analyzer failed to obtain an Autodiscover XML response.
> Additional Details
> An HTTP 500 response was returned from Unknown.
> 
> HTTP Response Headers:
> 
> X-API: http://www.tine20.org/apidocs/tine20/
> 
> Upgrade: h2
> 
> Upgrade: h2c
> 
> Connection: Upgrade
> 
> Connection: close
> 
> Transfer-Encoding: chunked
> 
> Content-Type: text/html; charset=UTF-8
> 
> Date: Mon, 04 Jan 2021 20:25:10 GMT
> 
> Server: Apache

**Comment by lab-at-nohl** [comment] 2021-01-05 11:10
I am sorry, I do not fully understand what you are trying to achieve. Since you need to capture virtual URI like `/Autodiscover/Autodiscover.xml` I assume the .htaccess-file must be located in the web-root `/`. And you do not use enclosing `<Location>` or `<Directory>` (the latter is implied by the location of the .htaccess file). Are you sure Location is forbidden by your hoster, why? 

> An HTTP 500 response was returned from Unknown.

That means your sever has a misconfiguration, http status 500... I guess that is caused by an invalid path given to Tine 2.0. Otherwise, if not Tine 2.0 would handle it, you would expect status 404 (not found). Use Tine 2.0 logging to see what's happening...

Please read the Apache manual for Rewrite carefully. Maybe you need (due to the missing Location) something like `RewriteBase /` (with full path in the Rule). Or try to give a relative path in `RewriteRule` (no leading `/`). Actually at this point you can only try around... As a starting point I would ensure ActiveSync is working (by entering https://mydomain.tld/Microsoft-Server-ActiveSync in a browser - which should return a "It works!"), then take over this `RewriteRule` accordingly.
