### ISSUE TITLE
0012752:
Wrong Order of Priority

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#6310] opened 2018-06-09 16:45 UTC
**Reported by sunghost on 6 Mar 2017 09:59**

**Version:** 2017.02.1 Community Edition

Hi,
if you order the column Priority in Tasks, it will sort it for alphanum (a-z), but not for the priority itself. This is in German Language, so i never testet it in english. Actuall it sorts dringend, normal, niedrig, hoch. Correct would be dringend,high,normal,niedrig.

**Comment by pschuele** [comment] 2018-07-12 16:13
duplicate of 2931

**Closed by pschuele** 2018-07-12 16:13 UTC
Labels: Mantis, Tasks, high priority
