### ISSUE TITLE
0005042:
Force Reload of IMAP Folderlist after loading the EXTJS gui

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2578] opened 2018-06-08 23:28 UTC
**Reported by kaystrobach on 3 Nov 2011 07:24**

**Version:** Maischa (2011-05-5)

working as team on a shared imap account causes problems because of missing autoreload of folderlist (should be also done after switching tabs periodically)

**Comment by Gloirin** [comment] 2018-06-09 22:51
Related to #1206

**Comment by pschuele** [comment] 2018-07-02 13:40
duplicate of #1669 (and others)

**Closed by pschuele** 2018-07-02 13:40 UTC
Labels: Bug, Felamimail, Mantis
