### ISSUE TITLE
0013854:
Can't update Email Accounts without Sieve Server

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#6851] opened 2018-06-09 19:22 UTC
**Reported by psieg on 3 May 2018 16:07**

**Version:** 2018.02.3 Community Edition

I am unable to update the email account of a user in a setup that does not use sieve.
Hitting save results in 

 Tinebase_Exception::logExceptionToLogger::133 Felamimail_Exception_Sieve -&gt; Could not authenticate with user XXX (cannot write - connection closed?).

because the sieve server hostname is &quot;&quot;.
The sieve notification email is empty. Debugging leads to
Felamimail/Controller/Account.php line 452:

 452         if ($updatedRecord-&gt;sieve_notification_email != $currentRecord-&gt;sieve_notification_email) {

In this case, the left side was &quot;&quot; but the right side was NULL, leading this function to believe a valid sieve configuration exists and should be updated, which fails, lacking a sieve server.

I am not sure if this difference is due to an update, but I did not manually change the database.

**Steps to reproduce:** * Setup an email account with IMAP/SMTP but no sieve (before an update?)
* Try to change the IMAP password later

Expected: Password change
Actual: Error message about connection that does not hint at Sieve being the problem

**Comment by Gloirin** [comment] 2018-06-11 13:01
**Comment posted by psieg on 3 May 2018 16:08**

Of course the original line contains !==. As a workaround, I used !=, which allowed me to update the account in question.

**Comment by Ichwersonsttttttttttttttttttttt** [comment] 2020-02-26 18:00
The same Problem her
external IMAP / SMTP accounts
When i make a Change at the mail-account i get a erro

"   Sieve-Error      
Could not authenticate with user XXXXX (cannot write -connection closed?)  "

delet the Sieve setting not help

**Comment by pschuele** [comment] 2020-02-28 07:48
thanks for the report - I'll have a look

**Comment by pschuele** [comment] 2020-02-28 08:07
hi, I could not reproduce the error. could you please attach a stacktrace/DEBUG-log of the error?

**Comment by lab-at-nohl** [comment] 2020-02-28 17:52
I can reproduce. Please find the log attached. 
[tine20.log.txt](https://github.com/tine20/tine20/files/4268349/tine20.log.txt)

```
2a3037 65fbb username - 2020-02-28T17:37:12+00:00 NOTICE (5): Tinebase_Exception::logExceptionToLogger::133 Felamimail_Exception_Sieve -> Could not authenticate with user email.user (cannot write - connection closed?).
2a3037 65fbb username - 2020-02-28T17:37:12+00:00 NOTICE (5): Tinebase_Exception::logExceptionToLogger::155 #0 .../Felamimail/Backend/SieveFactory.php(46): Felamimail_Backend_Sieve->__construct(Array)
#1 .../Felamimail/Controller/Sieve.php(213): Felamimail_Backend_SieveFactory::factory(Object(Felamimail_Model_Account))
#2 .../Felamimail/Controller/Sieve.php(164): Felamimail_Controller_Sieve->_setSieveBackendAndAuthenticate(Object(Felamimail_Model_Account))
#3 .../Felamimail/Controller/Sieve.php(149): Felamimail_Controller_Sieve->_getServerSieveScript(Object(Felamimail_Model_Account))
#4 .../Felamimail/Controller/Sieve.php(767): Felamimail_Controller_Sieve->getSieveScript(Object(Felamimail_Model_Account))
#5 .../Felamimail/Controller/Sieve.php(818): Felamimail_Controller_Sieve->_updateScriptParts(Object(Felamimail_Model_Account), Object(Tinebase_Record_RecordSet), 'autoMoveNotific...')
#6 .../Felamimail/Controller/Account.php(1026): Felamimail_Controller_Sieve->updateAutoMoveNotificationScript(Object(Felamimail_Model_Account))
#7 .../Tinebase/Controller/Record/Abstract.php(1190): Felamimail_Controller_Account->_inspectAfterUpdate(Object(Felamimail_Model_Account), Object(Felamimail_Model_Account), Object(Felamimail_Model_Account))
#8 .../Tinebase/Frontend/Json/Abstract.php(296): Tinebase_Controller_Record_Abstract->update(Object(Felamimail_Model_Account))
#9 .../Felamimail/Frontend/Json.php(557): Tinebase_Frontend_Json_Abstract->_save(Array, Object(Felamimail_Controller_Account), 'Account')
#10 .../vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Felamimail_Frontend_Json->saveAccount(Array, true)
#11 .../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch(Object(Zend_Server_Method_Definition), Array)
#12 .../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle()
#13 .../Tinebase/Server/Json.php(396): Zend_Json_Server->handle(Object(Zend_Json_Server_Request))
#14 .../Tinebase/Server/Json.php(167): Tinebase_Server_Json->_handle(Object(Zend_Json_Server_Request))
#15 .../Tinebase/Core.php(267): Tinebase_Server_Json->handle(Object(Tinebase_Http_Request))
#16 .../index.php(24): Tinebase_Core::dispatchRequest()
#17 {main}
2a3037 65fbb username - 2020-02-28T17:37:12+00:00 INFO (6): Tinebase_TransactionManager::rollBack::213  rollBack request, rollBack all transactionables
2a3037 65fbb username - 2020-02-28T17:37:12+00:00 NOTICE (5): Tinebase_Server_Json::_handleException::426 Felamimail_Exception_Sieve -> Could not authenticate with user email.user (cannot write - connection closed?).
```

The hostname on the tab sieve in account settings is empty, indeed. 

Regards
J.

**Comment by Ichwersonsttttttttttttttttttttt** [comment] 2020-02-29 06:46
`------------ xxxxxxx - 2020-02-29T06:37:13+00:00 NOTICE (5): Tinebase_Exception::logExceptionToLogger::133 Felamimail_Exception_Sieve -> Could not authenticate with user xxxxxxxx@xxxxxxx.com (cannot write - connection closed?).
------------ xxxxxxx - 2020-02-29T06:37:13+00:00 NOTICE (5): Tinebase_Exception::logExceptionToLogger::155 #0 .../Felamimail/Backend/SieveFactory.php(46): Felamimail_Backend_Sieve->__construct(Array)
#1 .../Felamimail/Controller/Sieve.php(213): Felamimail_Backend_SieveFactory::factory(Object(Felamimail_Model_Account))
#2 .../Felamimail/Controller/Sieve.php(164): Felamimail_Controller_Sieve->_setSieveBackendAndAuthenticate(Object(Felamimail_Model_Account))
#3 .../Felamimail/Controller/Sieve.php(149): Felamimail_Controller_Sieve->_getServerSieveScript(Object(Felamimail_Model_Account))
#4 .../Felamimail/Controller/Sieve.php(767): Felamimail_Controller_Sieve->getSieveScript(Object(Felamimail_Model_Account))
#5 .../Felamimail/Controller/Sieve.php(818): Felamimail_Controller_Sieve->_updateScriptParts(Object(Felamimail_Model_Account), Object(Tinebase_Record_RecordSet), 'autoMoveNotific...')
#6 .../Felamimail/Controller/Account.php(1026): Felamimail_Controller_Sieve->updateAutoMoveNotificationScript(Object(Felamimail_Model_Account))
#7 .../Tinebase/Controller/Record/Abstract.php(1190): Felamimail_Controller_Account->_inspectAfterUpdate(Object(Felamimail_Model_Account), Object(Felamimail_Model_Account), Object(Felamimail_Model_Account))
#8 .../Tinebase/Frontend/Json/Abstract.php(296): Tinebase_Controller_Record_Abstract->update(Object(Felamimail_Model_Account))
#9 .../Felamimail/Frontend/Json.php(557): Tinebase_Frontend_Json_Abstract->_save(Array, Object(Felamimail_Controller_Account), 'Account')
#10 .../vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Felamimail_Frontend_Json->saveAccount(Array, true)
#11 .../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch(Object(Zend_Server_Method_Definition), Array)
#12 .../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle()
#13 .../Tinebase/Server/Json.php(396): Zend_Json_Server->handle(Object(Zend_Json_Server_Request))
#14 .../Tinebase/Server/Json.php(167): Tinebase_Server_Json->_handle(Object(Zend_Json_Server_Request))
#15 .../Tinebase/Core.php(267): Tinebase_Server_Json->handle(Object(Tinebase_Http_Request))
#16 .../index.php(24): Tinebase_Core::dispatchRequest()
#17 {main}
`

**Comment by Ichwersonsttttttttttttttttttttt** [comment] 2020-02-29 07:10
```xxxxxxx - 2020-02-29T06:37:13+00:00 NOTICE (5): Tinebase_Exception::logExceptionToLogger::133 Felamimail_Exception_Sieve -> Could not authenticate with user xxxxxxxx (cannot write - connection closed?).
xxxxxxx - 2020-02-29T06:37:13+00:00 NOTICE (5): Tinebase_Exception::logExceptionToLogger::155 #0 .../Felamimail/Backend/SieveFactory.php(46): Felamimail_Backend_Sieve->__construct(Array)
#1 .../Felamimail/Controller/Sieve.php(213): Felamimail_Backend_SieveFactory::factory(Object(Felamimail_Model_Account))
#2 .../Felamimail/Controller/Sieve.php(164): Felamimail_Controller_Sieve->_setSieveBackendAndAuthenticate(Object(Felamimail_Model_Account))
#3 .../Felamimail/Controller/Sieve.php(149): Felamimail_Controller_Sieve->_getServerSieveScript(Object(Felamimail_Model_Account))
#4 .../Felamimail/Controller/Sieve.php(767): Felamimail_Controller_Sieve->getSieveScript(Object(Felamimail_Model_Account))
#5 .../Felamimail/Controller/Sieve.php(818): Felamimail_Controller_Sieve->_updateScriptParts(Object(Felamimail_Model_Account), Object(Tinebase_Record_RecordSet), 'autoMoveNotific...')
#6 .../Felamimail/Controller/Account.php(1026): Felamimail_Controller_Sieve->updateAutoMoveNotificationScript(Object(Felamimail_Model_Account))
#7 .../Tinebase/Controller/Record/Abstract.php(1190): Felamimail_Controller_Account->_inspectAfterUpdate(Object(Felamimail_Model_Account), Object(Felamimail_Model_Account), Object(Felamimail_Model_Account))
#8 .../Tinebase/Frontend/Json/Abstract.php(296): Tinebase_Controller_Record_Abstract->update(Object(Felamimail_Model_Account))
#9 .../Felamimail/Frontend/Json.php(557): Tinebase_Frontend_Json_Abstract->_save(Array, Object(Felamimail_Controller_Account), 'Account')
#10 .../vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Felamimail_Frontend_Json->saveAccount(Array, true)
#11 .../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch(Object(Zend_Server_Method_Definition), Array)
#12 .../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle()
#13 .../Tinebase/Server/Json.php(396): Zend_Json_Server->handle(Object(Zend_Json_Server_Request))
#14 .../Tinebase/Server/Json.php(167): Tinebase_Server_Json->_handle(Object(Zend_Json_Server_Request))
#15 .../Tinebase/Core.php(267): Tinebase_Server_Json->handle(Object(Tinebase_Http_Request))
#16 .../index.php(24): Tinebase_Core::dispatchRequest()
```

**Comment by pschuele** [comment] 2020-03-03 07:35
I wrote a fix for this. coming soon ...

**Closed** 2020-03-05 15:46 UTC
Labels: Bug, Felamimail, Mantis
