### ISSUE TITLE
Failed to upgrade Tinebase

### ISSUE THREAD

**Issue by mzch** [tine20/tine20#7226] opened 2020-10-30 05:54 UTC
When upgrading Tine from `2020082` to `2020083`, or `2020084`, Tinebase failed to be upgraded.

```php
An exception occurred while executing 'ALTER TABLE `tine20_tree_nodes` DROP FOREIGN KEY `tine20_tree_nodes::parent_id--tree_nodes::id`': SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN KEY `tine20_tree_nodes::parent_id--tree_nodes::id`; check that it exists

.../vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException()
.../vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(855): Doctrine\DBAL\DBALException::driverExceptionDuringQuery()
.../vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php(843): Doctrine\DBAL\Connection->executeQuery()
.../Setup/SchemaTool.php(146): Doctrine\ORM\Tools\SchemaTool->updateSchema()
.../Tinebase/Setup/Update/14.php(29): Setup_SchemaTool::updateSchema()
.../Setup/Controller.php(556): Tinebase_Setup_Update_14->update001()
.../Setup/Frontend/Json.php(118): Setup_Controller->updateApplications()
.../vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Setup_Frontend_Json->updateApplications()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle()
.../Setup/Server/Json.php(90): Zend_Json_Server->handle()
.../Setup/Core.php(117): Setup_Server_Json->handle()
.../setup.php(14): Setup_Core::dispatchRequest()
```

- PHP: 7.3.19
- MariaDB: 10.5.6

**Comment by ravermeister** [comment] 2020-10-30 23:30
maybe a duplicate of #7225

**Comment by pschuele** [comment] 2020-11-05 08:40
yup, it's a duplicate. closing this.

**Closed by pschuele** 2020-11-05 08:40 UTC
