### ISSUE TITLE
2019.08.4 update fails with Tinebase_Exception_NotFound

### ISSUE THREAD

**Issue by shochdoerfer** [tine20/tine20#7113] opened 2019-11-23 09:03 UTC
Whilst trying to update from 2018.08.4 to 2019.08.4 I run into the following exception:
```
Tinebase_Exception_NotFound: user with userid setupuser not found in
/var/www/html/Tinebase/User/Ldap.php:728
Stack trace:
#0 /var/www/html/Tinebase/User/Ldap.php(829): Tinebase_User_Ldap->_getMetaData(Object(Tinebase_Model_FullUser))
#1 /var/www/html/Addressbook/Controller/Contact.php(1112): Tinebase_User_Ldap->updateContactFromSyncBackend(Object(Tinebase_Model_FullUser),
Object(Addressbook_Model_Contact))
#2 /var/www/html/Calendar/Controller/MSEventFacade.php(117): Addressbook_Controller_Contact->inspectAddUser(Object(Tinebase_Model_FullUser),
Object(Tinebase_Model_FullUser))
#3 /var/www/html/Calendar/Controller/Event.php(111): Calendar_Controller_MSEventFacade::getCurrentUserContactId()
#4 /var/www/html/Calendar/Controller/Event.php(131): Calendar_Controller_Event->__construct()
#5 /var/www/html/Tinebase/Core.php(443): Calendar_Controller_Event::getInstance()
#6 /var/www/html/Tinebase/Container.php(1256): Tinebase_Core::getApplicationInstance('Calendar_Model_...', '', true)
#7 /var/www/html/Tinebase/Container.php(1199): Tinebase_Container->deleteContainerContents(Object(Tinebase_Model_Container),
true)
#8 /var/www/html/Tinebase/Container.php(2316): Tinebase_Container->deleteContainer('1555', true)
#9 /var/www/html/Calendar/Setup/Update/12.php(93): Tinebase_Container->deleteDuplicateContainer(Object(Tinebase_Model_Application))
#10 /var/www/html/Setup/Controller.php(555): Calendar_Setup_Update_12->update005()
#11 /var/www/html/Setup/Frontend/Cli.php(467): Setup_Controller->updateApplications()
#12 /var/www/html/Setup/Frontend/Cli.php(451): Setup_Frontend_Cli->_updateApplications()
#13 /var/www/html/Setup/Frontend/Cli.php(81): Setup_Frontend_Cli->_update(Object(Zend_Console_Getopt))
#14 /var/www/html/Setup/Server/Cli.php(141): Setup_Frontend_Cli->handle(Object(Zend_Console_Getopt))
#15 /var/www/html/Setup/Core.php(117): Setup_Server_Cli->handle()
#16 /var/www/html/setup.php(14): Setup_Core::dispatchRequest()
#17 {main}
```

Technically it makes sense as the setupuser is not listed in LDAP, I am wondering why it is tried to access the setupuser in that place.

**Comment by koelschejung74** [comment] 2019-11-24 08:05
can you try update to 2019.08.1 and then to 04?

**Comment by paulmhh** [comment] 2019-11-24 13:51
the issue is that your setup user does not have a contact. Easiest solution would be to delete the setup user before upgrading. Maybe you can do it tine20 in the admin area, not sure. If you can't, just delete it in the tine20_accounts table, username "setupuser".

Upon running setup.php --update it will be recreated and then it will properly create the addressbook contact for the setup user too.

Read the code, pretty sure about this. Will add some code to fix this automatically

**Comment by paulmhh** [comment] 2019-11-24 14:01
hmm eventually there is a code path that leads to the creation of the setupuser without a adb contact if you have an ldap user backend ... so deleting the user might not help in that case, wrote a fix though, will let you know once its merged

**Comment by shochdoerfer** [comment] 2019-11-24 16:35
No worries, disabling the migration worked for now. Thanks for trying to fix this.

**Closed** 2019-12-11 13:51 UTC
