### ISSUE TITLE
Tine not loading in Internet Explorer 11

### ISSUE THREAD

**Issue by Shotweb** [tine20/tine20#6875] opened 2018-06-25 14:23 UTC
We are running Tine 2018.02.6. The Tine interface does not load at all on Internet Explorer 11; works fine in other browsers. IE's debugger console says "Expected ':' index.php (1,1179336)", which is this error: https://docs.microsoft.com/en-us/scripting/javascript/misc/expected-colon

The code in question seems to be the getCompressedWidth(e,t) in this snippet from one of the two(?) index.php I see in the debugger (that's what the debugger sends me to):
getCompressedWidth(e,t){var n=window.lodash,i=0,A=n.groupBy(e),a=n.uniq([].concat(e).sort(function(e,t){return e-t})),o=a[a.length-1],r=A[o].length,s=Math.min(t,a.length>1?(a[a.length-1]-a[a.length-2])*r:a[0]*r),l=n.map(e,function(e){var t=e;return e==o&&(i+=e-(t=e-s/r)),t});

I don't see this error in other browser's debuggers so I'm guessing that's the issue, but I don't know much about coding.

**Comment by pschuele** [comment] 2018-06-26 05:12
duplicate of #6877

**Closed by pschuele** 2018-06-26 05:12 UTC
