### ISSUE TITLE
DAVx5 only show personal calendar

### ISSUE THREAD

**Issue by crosenbe** [tine20/tine20#7478] opened 2023-08-25 06:49 UTC
With release 2022.12.1 DAVx5 only shows the personal calendar. The complete shared folder is ignored. This seems to be a specific behavior of DAVx5 because TB see also the shared calendars.

**Comment by crosenbe** [comment] 2023-08-25 14:19
If i call https://tine.foo.bar/calendars i see a personal calendar and a shared folder. Inside the shared folders the shared calendars are shown and inside of this subfolders there are multiple entries, looks like <hash values>.ics.

Two of them are downloadable, others not and produce following error message.

```
<d:error>
<s:exception>Sabre\DAV\Exception\NotFound</s:exception>
<s:message>Object not found</s:message>
</d:error>
```

**Comment by lab-at-nohl** [comment] 2023-08-26 11:38
Actually, if the ICS is shown in the list, it should be accessible. Can you provide a log file level DEBUG? To show the reason why.

**Comment by crosenbe** [comment] 2023-08-27 10:28
It seems a wrong URL is provided. the hash 64a6c30d305c0ff1075252cc93e5105b8c33618d is the field list_id of the entry in tine20_groups. I assume DAVx5 stop working and fetching more information after this error.

`<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:card="urn:ietf:params:xml:ns:carddav" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:owncloud="http://owncloud.org/ns"><d:response><d:href>/principals/groups/64a6c30d305c0ff1075252cc93e5105b8c33618d/</d:href><d:propstat><d:prop><d:group-membership/><d:displayname>Foobar (Gruppe)</d:displayname><cal:calendar-home-set><d:href>/calendars/64a6c30d305c0ff1075252cc93e5105b8c33618d/</d:href></cal:calendar-home-set><cs:calendar-proxy-read-for/><cs:calendar-proxy-write-for/></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response></d:multistatus>`

```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>Directory calendars/64a6c30d305c0ff1075252cc93e5105b8c33618d not found</s:message>
  <s:file>/opt/tine/2022.12.1/Tinebase/WebDav/Collection/AbstractContainerTree.php</s:file>
  <s:line>241</s:line>
  <s:code>0</s:code>
  <s:stacktrace>#0 /opt/tine/2022.12.1/Tinebase/WebDav/Collection/AbstractContainerTree.php(199): Tinebase_WebDav_Collection_AbstractContainerTree-&gt;_getToplevelTree()
#1 /opt/tine/2022.12.1/Calendar/Frontend/WebDAV.php(77): Tinebase_WebDav_Collection_AbstractContainerTree-&gt;getChild()
#2 /opt/tine/2022.12.1/vendor/sabre/dav/lib/Sabre/DAV/ObjectTree.php(72): Calendar_Frontend_WebDAV-&gt;getChild()
#3 /opt/tine/2022.12.1/vendor/sabre/dav/lib/Sabre/DAV/Server.php(1473): Sabre\DAV\ObjectTree-&gt;getNodeForPath()
#4 /opt/tine/2022.12.1/vendor/sabre/dav/lib/Sabre/DAV/Server.php(723): Sabre\DAV\Server-&gt;getPropertiesForPath()
#5 [internal function]: Sabre\DAV\Server-&gt;httpPropfind()
#6 /opt/tine/2022.12.1/vendor/sabre/dav/lib/Sabre/DAV/Server.php(474): call_user_func()
#7 /opt/tine/2022.12.1/vendor/sabre/dav/lib/Sabre/DAV/Server.php(214): Sabre\DAV\Server-&gt;invokeMethod()
#8 /opt/tine/2022.12.1/Tinebase/Server/WebDAV.php(296): Sabre\DAV\Server-&gt;exec()
#9 /opt/tine/2022.12.1/Tinebase/Core.php(271): Tinebase_Server_WebDAV-&gt;handle()
#10 /opt/tine/2022.12.1/index.php(24): Tinebase_Core::dispatchRequest()
#11 {main}</s:stacktrace>
</d:error>
```

**Comment by lab-at-nohl** [comment] 2023-08-27 13:21
Ok but a log file level DEBUG would help to see what's going on in Tine internally. 

Also, do you use the regular DAVx5 client? I wouldn't have expected that the proxy directories are used (which may also be the consequence of not finding groups).

**Comment by crosenbe** [comment] 2023-08-27 15:30
DAVx5 4.3.5.2-ose. 

The log lines above are part of the DEBUG log, but it's more than 2k lines. What kind of lines i have to search?

**Comment by lab-at-nohl** [comment] 2023-08-27 22:47
> What kind of lines i have to search?

I need the the requests that eventually leads to the stack trace you provided. Probably it is more than one request because DAVx5 will do some tests to find the calendars before requesting the missing one. Can't you limit it by user?

**Comment by crosenbe** [comment] 2023-08-28 05:57
[debug.log](https://github.com/tine20/tine20/files/12450743/debug.log)

**Comment by lab-at-nohl** [comment] 2023-08-28 11:18
I couldn't find a stack trace or error in the log. 

However, is the problematic group "visible"? A setting in the groups tab.

**Comment by crosenbe** [comment] 2023-08-28 12:24
There are three groups, all of them are visible. But visibility is only relevant with address books?

**Comment by crosenbe** [comment] 2023-09-01 11:03
Whats about line 1514 ...
```

<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>Directory calendars/role-2 not found</s:message>
  <s:file>/opt/tine/2022.12.1/Tinebase/WebDav/Collection/AbstractContainerTree.php</s:file>
  <s:line>241</s:line>
  <s:code>0</s:code>
  <s:stacktrace>#0 /opt/tine/2022.12.1/Tinebase/WebDav/Collection/AbstractContainerTree.php(199): Tinebase_WebDav_Collection_AbstractContainerTree-&gt;_getToplevelTree()
#1 /opt/tine/2022.12.1/Calendar/Frontend/WebDAV.php(77): Tinebase_WebDav_Collection_AbstractContainerTree-&gt;getChild()
#2 /opt/tine/2022.12.1/vendor/sabre/dav/lib/Sabre/DAV/ObjectTree.php(72): Calendar_Frontend_WebDAV-&gt;getChild()
#3 /opt/tine/2022.12.1/vendor/sabre/dav/lib/Sabre/DAV/Server.php(1473): Sabre\DAV\ObjectTree-&gt;getNodeForPath()
#4 /opt/tine/2022.12.1/vendor/sabre/dav/lib/Sabre/DAV/Server.php(723): Sabre\DAV\Server-&gt;getPropertiesForPath()
#5 [internal function]: Sabre\DAV\Server-&gt;httpPropfind()
#6 /opt/tine/2022.12.1/vendor/sabre/dav/lib/Sabre/DAV/Server.php(474): call_user_func()
#7 /opt/tine/2022.12.1/vendor/sabre/dav/lib/Sabre/DAV/Server.php(214): Sabre\DAV\Server-&gt;invokeMethod()
#8 /opt/tine/2022.12.1/Tinebase/Server/WebDAV.php(296): Sabre\DAV\Server-&gt;exec()
#9 /opt/tine/2022.12.1/Tinebase/Core.php(271): Tinebase_Server_WebDAV-&gt;handle()
#10 /opt/tine/2022.12.1/index.php(24): Tinebase_Core::dispatchRequest()
#11 {main}</s:stacktrace>
</d:error>
```

**Comment by lab-at-nohl** [comment] 2023-09-01 20:31
Ok, I see/saw that. But I cannot see that an non-existing URL was called. Can you open all the URLs found in your log in the Browser? Try these:

```urls
https://[your-domain]/principals/groups/64a6c30d305c0ff1075252cc93e5105b8c33618d/
https://[your-domain]/calendars/64a6c30d305c0ff1075252cc93e5105b8c33618d/
https://[your-domain]/principals/groups/role-2
https://[your-domain]/calendars/role-2/
https://[your-domain]/principals/users/2/
```

Who is `913c9ca7d977cd734a2fad30f09fbc8095ef1578` - probably a user?

Any custom defined Roles? I have user, admin and replication. Those I can open in calendars (not sure why but they exist). The Role we look for should have the id 2. 

When I scrolled thru your log I saw that e.g. "Users (Gruppe)" was opened without flaws. Thus, some groups works. Can you check your configuration that Groups and Roles do not have a member that does not exist anymore (or similar)?

**Comment by crosenbe** [comment] 2023-09-01 22:06
I have one additional custom role defined. The role with ID 2 is the user role.
I didn't find a user, group, role with ID `913c9ca7d977cd734a2fad30f09fbc8095ef1578`.

Please see the result of the URL calls below ...

`https://[your-domain]/principals/groups/64a6c30d305c0ff1075252cc93e5105b8c33618d/`
This is callable and contains the two objects calendar-proxy-read and calendar-proxy-write

`https://[your-domain]/calendars/64a6c30d305c0ff1075252cc93e5105b8c33618d/`
This is not callable "Sabre\DAV\Exception\NotFound"

`https://[your-domain]/principals/groups/role-2`
This is callable and contains the two objects calendar-proxy-read and calendar-proxy-write

`https://[your-domain]/calendars/role-2/`
This is not callable "Sabre\DAV\Exception\NotFound"

`https://[your-domain]/principals/users/2/`
This is callable and contains the two objects calendar-proxy-read and calendar-proxy-write

**Comment by lab-at-nohl** [comment] 2023-09-02 11:23
Hm, since I cannot reproduce the behaviour yet, I can only guess. Have you tried to edit the groups and roles that belong to the respective list_id? Like remove a user, save, add it again and save again...

Also maybe ACL involved?

**Comment by crosenbe** [comment] 2023-09-04 07:56
The ID `64a6c30d305c0ff1075252cc93e5105b8c33618d `is a defined group.

`<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:card="urn:ietf:params:xml:ns:carddav" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:owncloud="http://owncloud.org/ns"><d:response><d:href>/principals/users/2/</d:href><d:propstat><d:prop><d:group-membership><d:href>/principals/groups/81e870c5116087e9205ac76f0626ce97b8d2fc19</d:href><d:href>/principals/groups/a8b09c4152a1f553ed4bfea4fcc1f7f63476bb61</d:href><d:href>/principals/groups/64a6c30d305c0ff1075252cc93e5105b8c33618d</d:href><d:href>/principals/groups/role-2</d:href><d:href>/principals/groups/role-4</d:href><d:href>/principals/users/shared/calendar-proxy-write</d:href></d:group-membership><d:displayname>Me, Its</d:displayname><cal:calendar-home-set><d:href>/calendars/2/</d:href></cal:calendar-home-set><cs:calendar-proxy-read-for/><cs:calendar-proxy-write-for><d:href>/principals/users/shared</d:href></cs:calendar-proxy-write-for></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response></d:multistatus>
`

So far so good, later in the log Tine send following response ....

`<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:card="urn:ietf:params:xml:ns:carddav" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:owncloud="http://owncloud.org/ns"><d:response><d:href>/principals/groups/64a6c30d305c0ff1075252cc93e5105b8c33618d/</d:href><d:propstat><d:prop><d:group-membership/><d:displayname>FooBarA (Gruppe)</d:displayname><cal:calendar-home-set><d:href>/calendars/64a6c30d305c0ff1075252cc93e5105b8c33618d/</d:href></cal:calendar-home-set><cs:calendar-proxy-read-for/><cs:calendar-proxy-write-for/></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response></d:multistatus>`

Why Tine transmit the calendar-home-set to `/calendars/64a6c30d305c0ff1075252cc93e5105b8c33618d`? This calendar does not exist of course because the ID is a group.

**Comment by lab-at-nohl** [comment] 2023-09-11 22:22
As far as I can see, the home-set and the read-/write-proxy are the same with my Tine 2022.12.1. Also DAVx5 shows all groups and roles under `/principals`, I tried two different users. As I said, I can only guess until I can reproduce it. 

I agree that something is going wrong. Could you try to find the non existing link in the browser (just open the location /principals and click on each folder/link). I would like to see a debug log opening such a link. One might expect a lot of errors then...

**Comment by crosenbe** [comment] 2023-09-15 12:29
I tried to reproduce a stacktrace by clicking through the Sabre DAV web interface, without any success. I don't know why DAVx5 try to open paths which are never provided by the web interface. 

`INFO (6): Tinebase_WebDav_Collection_AbstractContainerTree::_getToplevelTree::240 Directory calendars/role-4 not found`

This message is true, the directory does not exist. But it was also never tried to access using the web interface. But clicking on events bring some errors which are not shown in the log file but as direct result in the browser.

```
<d:error>
<s:exception>Sabre\DAV\Exception\NotFound</s:exception>
<s:message>Object not found</s:message>
<s:file>
/opt/tine/2022.12.1/Calendar/Frontend/WebDAV/Container.php
</s:file>
<s:line>90</s:line>
<s:code>0</s:code>
<s:stacktrace>
#0 /opt/tine/2022.12.1/vendor/sabre/dav/lib/Sabre/DAV/ObjectTree.php(72): Calendar_Frontend_WebDAV_Container->getChild()
#1 /opt/tine/2022.12.1/vendor/sabre/dav/lib/Sabre/DAV/Server.php(525): Sabre\DAV\ObjectTree->getNodeForPath() 
#2 [internal function]: Sabre\DAV\Server->httpGet() 
#3 /opt/tine/2022.12.1/vendor/sabre/dav/lib/Sabre/DAV/Server.php(474): call_user_func() 
#4 /opt/tine/2022.12.1/vendor/sabre/dav/lib/Sabre/DAV/Server.php(214): Sabre\DAV\Server->invokeMethod() 
#5 /opt/tine/2022.12.1/Tinebase/Server/WebDAV.php(296): Sabre\DAV\Server->exec() 
#6 /opt/tine/2022.12.1/Tinebase/Core.php(271): Tinebase_Server_WebDAV->handle() 
#7 /opt/tine/2022.12.1/index.php(24): Tinebase_Core::dispatchRequest() 
#8 {main}
</s:stacktrace>
</d:error>
```

Regarding your question of clicking all principle entries, no error in log and no error in the web interface.

**Comment by crosenbe** [comment] 2023-09-15 13:06
Additional information, there is also no single stacktrace using Thunderbird. I have a bit the feeling DAVx5 need to investigated more than Tine.

**Comment by lab-at-nohl** [comment] 2023-09-15 15:55
Yes, you can export a log from DAVx5 and see (show). It was very hard to find but somewhere in the general settings (only visible if not an account is selected). When adding a new account to DAVx5, have you support for tasks enabled? 

It might be that Thunderbird just ignors the principals. Has the Role with id 4 existed before? If so, try to delete session files, maybe old and new data is mixed. 

Below I manually formatted what Tine 2.0 is offering in its initial response (from your log). Thus, Role with id 4 stems from the initial request (I wonder if the Role may be not fully expunged but only marked as deleted?): 

```xml
<?xml version="1.0" encoding="utf-8"?>

<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:card="urn:ietf:params:xml:ns:carddav" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:owncloud="http://owncloud.org/ns">

<d:response>
  <d:href>/principals/users/2/</d:href>
  <d:propstat>
    <d:prop>
      <d:group-membership>
        <d:href>/principals/groups/81e870c5116087e9205ac76f0626ce97b8d2fc19</d:href>
        <d:href>/principals/groups/a8b09c4152a1f553ed4bfea4fcc1f7f63476bb61</d:href>
        <d:href>/principals/groups/64a6c30d305c0ff1075252cc93e5105b8c33618d</d:href>
        <d:href>/principals/groups/role-2</d:href>
        <d:href>/principals/groups/role-4</d:href>
        <d:href>/principals/users/shared/calendar-proxy-write</d:href>
      </d:group-membership>
      <d:displayname>Me, Its</d:displayname>
      <cal:calendar-home-set>
        <d:href>/calendars/2/</d:href>
      </cal:calendar-home-set>
      <cs:calendar-proxy-read-for/>
      <cs:calendar-proxy-write-for>
        <d:href>/principals/users/shared</d:href>
      </cs:calendar-proxy-write-for>
    </d:prop>
    <d:status>HTTP/1.1 200 OK</d:status>
  </d:propstat>
</d:response>

</d:multistatus>
```

**Comment by crosenbe** [comment] 2023-09-15 15:58
This is a DAVx5 log extract. A couple of calendars does not exist, following are available.

- /calendars/2/
- /calendars/shared/
- /calendars/2/30/
- /calendars/2/6/
- /calendars/2/7/

The others are not real but are delivered somehow.

```
09-15 15:31:01.054 22836 26804 V davx5   : [network.HttpClient] --> PROPFIND https://[your-domain]/calendars/2/ http/1.1
09-15 15:31:01.180 22836 26804 V davx5   : [network.HttpClient] --> PROPFIND https://[your-domain]/calendars/64a6c30d305c0ff1075252cc93e5105b8c33618d/ http/1.1
09-15 15:31:01.278 22836 26804 V davx5   : [network.HttpClient] --> PROPFIND https://[your-domain]/calendars/913c9ca7d977cd734a2fad30f09fbc8095ef1578/ http/1.1
09-15 15:31:01.365 22836 26804 V davx5   : [network.HttpClient] --> PROPFIND https://[your-domain]/calendars/a8b09c4152a1f553ed4bfea4fcc1f7f63476bb61/ http/1.1
09-15 15:31:01.441 22836 26804 V davx5   : [network.HttpClient] --> PROPFIND https://[your-domain]/calendars/calendar-proxy-write/ http/1.1
09-15 15:31:01.522 22836 26804 V davx5   : [network.HttpClient] --> PROPFIND https://[your-domain]/calendars/role-2/ http/1.1
09-15 15:31:01.595 22836 26804 V davx5   : [network.HttpClient] --> PROPFIND https://[your-domain]/calendars/role-4/ http/1.1
09-15 15:31:01.675 22836 26804 V davx5   : [network.HttpClient] --> PROPFIND https://[your-domain]/calendars/shared/ http/1.1
09-15 15:31:01.818 22836 26804 V davx5   : [network.HttpClient] --> PROPFIND https://[your-domain]/calendars/2/30/ http/1.1
09-15 15:31:01.916 22836 26804 V davx5   : [network.HttpClient] --> PROPFIND https://[your-domain]/calendars/2/6/ http/1.1
09-15 15:31:02.019 22836 26804 V davx5   : [network.HttpClient] --> PROPFIND https://[your-domain]/calendars/2/7/ http/1.1
```

**Comment by crosenbe** [comment] 2023-09-16 07:16
> Yes, you can export a log from DAVx5 and see (show). It was very hard to find but somewhere in the general settings (only visible if not an account is selected). When adding a new account to DAVx5, have you support for tasks enabled?

No, task support is disabled.

> It might be that Thunderbird just ignors the principals. Has the Role with id 4 existed before? If so, try to delete session files, maybe old and new data is mixed.

As already mentioned it seems DAVx5 also ignores it now, with the latest version and after removal and adding the account i see the calendars. But the stacktraces does still exist.
 
> Below I manually formatted what Tine 2.0 is offering in its initial response (from your log). Thus, Role with id 4 stems from the initial request (I wonder if the Role may be not fully expunged but only marked as deleted?):

The role with id 4 did exist before and is not deleted. But i used Timetracker in the past and this app was still enabled. In the meanwhile i disabled it. The tables are still there, i don't know if all relevant information were removed with disabling the application. I expected the removal of tables, but maybe this has to be done as a manual task because it would mean all data are gone if something disable and enable an application. This could be an unexpected behavior.

**Comment by pschuele** [comment] 2023-12-27 12:18
as we moved the issues, please open a new one here if the problem persists: https://github.com/tine-groupware/tine/issues.

**Closed by pschuele** 2023-12-27 12:18 UTC
