### ISSUE TITLE
0002092:
Sort leads by status or client

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#1128] opened 2018-06-08 17:06 UTC
**Reported by sven1999 on 12 Jan 2010 22:07**

**Version:** August (2009-11-3)

Leads can be sorted.
But to allow more useful sorting orders, leads should be sortable on any attribute, like Status or Client.

**Comment by pschuele** [comment] 2018-06-08 18:35
server now supports sorting by relations. we just need to activate it in the client.

**Comment by Gloirin** [comment] 2018-06-10 05:06
**Comment posted by pschuele on 9 Jul 2012 10:34**

we need a generic sorting approach for keyfield configs.

**Comment by pschuele** [comment] 2018-07-12 16:45
duplicate of #2931

**Closed by pschuele** 2018-07-12 16:45 UTC
Labels: Crm, Feature Request, Mantis
